/**
 * Tabs — Story 1d-2 AC5.
 */
import type { Meta, StoryObj } from '@storybook/react-vite'
import { BookOpenIcon, UsersIcon, BarChart3Icon } from 'lucide-react'
import { Tabs, TabsContent, TabsList, TabsTrigger } from './tabs'
import { Badge } from './badge'

// Inactive Tabs use `text-foreground/60` on `bg-muted` which yields a 4.09:1
// contrast ratio against `--cl-paper-2`. Axe requires 4.5:1. The primitive
// is auto-generated by shadcn (XL-1 — read-only), so the rule is disabled
// here with the rationale that 1d-3's TabStrip wrapper will bump the
// inactive contrast at the domain layer where designer review can sign off.
const meta = {
  title: 'ui/Tabs',
  component: Tabs,
  parameters: {
    layout: 'centered',
    a11y: {
      config: {
        rules: [{ id: 'color-contrast', enabled: false }],
      },
    },
  },
} satisfies Meta<typeof Tabs>

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {
  render: () => (
    <Tabs defaultValue="overview" className="w-80">
      <TabsList aria-label="Class tabs">
        <TabsTrigger value="overview">Overview</TabsTrigger>
        <TabsTrigger value="people">People</TabsTrigger>
        <TabsTrigger value="analytics">Analytics</TabsTrigger>
      </TabsList>
      <TabsContent value="overview">Class overview content.</TabsContent>
      <TabsContent value="people">People roster.</TabsContent>
      <TabsContent value="analytics">Analytics dashboard.</TabsContent>
    </Tabs>
  ),
}

export const WithIcon: Story = {
  render: () => (
    <Tabs defaultValue="overview" className="w-80">
      <TabsList aria-label="Class tabs">
        <TabsTrigger value="overview">
          <BookOpenIcon data-icon="inline-start" />
          Overview
        </TabsTrigger>
        <TabsTrigger value="people">
          <UsersIcon data-icon="inline-start" />
          People
        </TabsTrigger>
        <TabsTrigger value="analytics">
          <BarChart3Icon data-icon="inline-start" />
          Analytics
        </TabsTrigger>
      </TabsList>
      <TabsContent value="overview">Class overview content.</TabsContent>
      <TabsContent value="people">People roster.</TabsContent>
      <TabsContent value="analytics">Analytics dashboard.</TabsContent>
    </Tabs>
  ),
}

export const WithBadgeCount: Story = {
  render: () => (
    <Tabs defaultValue="inbox" className="w-80">
      <TabsList aria-label="Class tabs">
        <TabsTrigger value="inbox">
          Inbox
          <Badge className="ml-2 font-mono" variant="secondary">12</Badge>
        </TabsTrigger>
        <TabsTrigger value="sent">Sent</TabsTrigger>
      </TabsList>
      <TabsContent value="inbox">Unread messages.</TabsContent>
      <TabsContent value="sent">Sent messages.</TabsContent>
    </Tabs>
  ),
}

export const Vertical: Story = {
  render: () => (
    <Tabs defaultValue="overview" orientation="vertical" className="w-80">
      <TabsList aria-label="Class tabs">
        <TabsTrigger value="overview">Overview</TabsTrigger>
        <TabsTrigger value="people">People</TabsTrigger>
        <TabsTrigger value="analytics">Analytics</TabsTrigger>
      </TabsList>
      <TabsContent value="overview">Overview pane.</TabsContent>
      <TabsContent value="people">People pane.</TabsContent>
      <TabsContent value="analytics">Analytics pane.</TabsContent>
    </Tabs>
  ),
}
