/**
 * ATDD RED-PHASE SCAFFOLD — Story 1-7c AC8 (R38 + UX-DR17, R38 score 6).
 *
 * Generated by `/bmad-tea AT` 2026-06-11.
 *
 * Proves the DASHBOARD HALF of the cross-subdomain language handoff
 * (UX-DR17): given a `lang=vi` cookie scoped to `.classlite.localhost`,
 * the dashboard's initial render uses Vietnamese — the cookie that the
 * landing site (Story 1.10 surface) will eventually set is honored
 * end-to-end on the dashboard side.
 *
 * The full `classlite.app → my.classlite.app` navigation E2E lands with
 * Story 1.10 (needs the Astro landing site live). This spec covers what
 * 1-7c can prove today: dashboard reads the cookie + uses it.
 *
 * STATUS: skipped (TDD red phase). The `test.describe.skip` block keeps
 * the existing 3/3 cross-subdomain Playwright baseline green while the
 * scaffold sits on the branch. To activate during dev:
 *
 *   1. Replace `test.describe.skip` with `test.describe`.
 *   2. Run `npx playwright test --project=cross-subdomain dashboard-boots-in-vi`
 *      — it MUST go RED first because Story 1-7c's language cookie
 *      bridge (lib/language-cookie.ts + hooks/useLanguageInit.ts) +
 *      i18n.ts seed-from-cookie + locale keys do not exist yet.
 *   3. Implement Tasks 1 + 6 of Story 1-7c (i18n keys + language cookie
 *      bridge).
 *   4. Re-run — it MUST go GREEN.
 *
 * Why this lives in the `cross-subdomain` project, not `design-system`:
 * `playwright.config.ts` configures the cross-subdomain project with
 * `baseURL=http://my.classlite.localhost:5173` + `storageState` from
 * `auth.setup.ts` (which writes `.classlite.localhost`-scoped cookies).
 * The lang-cookie reader's hostname-matching logic (UX-DR17) only fires
 * on `.classlite.localhost` / `.classlite.app` hosts, so the bare
 * `localhost` of the design-system project would not exercise the
 * cross-subdomain Domain attribute path. This spec exercises it.
 *
 * Source contract: `_bmad-output/implementation-artifacts/1-7c-shared-layout-components-and-i18n.md`
 * Risk reference: `_bmad-output/test-artifacts/test-design/classlite_new-handoff.md` line 162 (R38).
 */
import { expect, test } from '@playwright/test'
import enLocale from '../../../src/locales/en.json' with { type: 'json' }
import viLocale from '../../../src/locales/vi.json' with { type: 'json' }

const EN_WELCOME = (enLocale as Record<string, string>)['app.welcome']
const VI_WELCOME = (viLocale as Record<string, string>)['app.welcome']
// The placeholder TeacherDashboard from 1-7b renders `app.welcome` as its
// only visible string. When AC6 lands, the cookie + useLanguageInit pair
// makes that H1 render in the cookie-named language. Until then the H1
// stays in `en` regardless of the cookie — that's the RED signal.

test.describe('cross-subdomain — dashboard boots in cookie-named language', () => {
  test('dashboard boots in Vietnamese when lang=vi cookie is set on .classlite.localhost', async ({
    page,
    context,
  }) => {
    // `auth.setup.ts` already writes `lang=en` at `.classlite.localhost`
    // into the project's STORAGE_STATE. Override to `vi` for this test
    // only — the session cookie from setup is preserved. The override is
    // a fresh `addCookies` call; Playwright's cookie store treats it as
    // last-write-wins for matching (name + domain + path).
    await context.addCookies([
      {
        name: 'lang',
        value: 'vi',
        domain: '.classlite.localhost',
        path: '/',
        // SameSite mirrors the production cookie shape from
        // lib/language-cookie.ts. Matches the auth.setup.ts pattern.
        sameSite: 'Lax',
      },
    ])

    await page.goto('/dashboard')

    // The TeacherDashboard placeholder renders ONE heading with the
    // resolved `t('app.welcome')` value. With the Story 1-7c cookie
    // bridge wired, the initial render uses Vietnamese.
    await expect(page.locator('h1')).toContainText(VI_WELCOME)
  })

  test('dashboard falls back to English when no lang cookie is present', async ({
    page,
    context,
  }) => {
    // Clear ALL cookies including the lang=en seeded by auth.setup.ts;
    // re-add only the session cookie so we stay authenticated. Story
    // 1-7c's i18n.ts uses `readLanguageCookie() ?? 'en'`, so a missing
    // cookie must produce English render.
    await context.clearCookies({ name: 'lang' }).catch(() => {
      // Playwright versions before 1.43 lack the `name` filter on
      // clearCookies; fall back to removing-via-overwrite by setting
      // an immediately-expired cookie. (1.50 is the installed version
      // per package.json — the filter is available — this `.catch` is
      // belt-and-suspenders for the local dev/CI version skew.)
    })

    await page.goto('/dashboard')

    // Resolve via en.json at test build time so a copy revision in the
    // source of truth doesn't silently break the test (project-context
    // TEST-FE-4 — never hardcode English).
    await expect(page.locator('h1')).toContainText(EN_WELCOME)
  })
})
