/**
 * ATDD RED-PHASE SCAFFOLD — Story 1-7c AC1 (R38 mitigation, score 6).
 *
 * Generated by `/bmad-tea AT` 2026-06-11.
 *
 * This is the WF-8-mandated ATDD red specimen for R38 ("i18n key missing in
 * vi.json — Vietnamese user sees raw key"). It enumerates every i18n key
 * Story 1-7c introduces and asserts BOTH en.json AND vi.json contain it.
 *
 * STATUS: skipped (TDD red phase). The `describe.skip` block keeps the
 * existing 100/100 vitest baseline green while the scaffold sits on the
 * branch alongside the story file. To activate during dev:
 *
 *   1. Replace `describe.skip` below with `describe`.
 *   2. Run `npx vitest run i18n-parity-coverage` — it MUST go RED first
 *      against the existing 3-key locale stubs.
 *   3. Add the keys to en.json + vi.json per Story 1-7c AC1 / Task 1.x.
 *   4. Re-run — it MUST go GREEN.
 *   5. Re-run `npm run i18n-parity` (the CI script) — also GREEN.
 *
 * If you activate this test and it does NOT go red against the baseline,
 * the assertI18nParity helper has been tampered with or the keys were
 * silently pre-seeded — investigate before unsuppressing.
 *
 * Source contract: `_bmad-output/implementation-artifacts/1-7c-shared-layout-components-and-i18n.md`
 * Risk reference: `_bmad-output/test-artifacts/test-design/classlite_new-handoff.md` line 162 (R38).
 */
import { describe, expect, test } from 'vitest'
import {
  assertI18nInterpolationParity,
  assertI18nParity,
} from '@/lib/test/i18n-parity'

/**
 * Every i18n key Story 1-7c introduces. Grouped by surface for readability.
 * Order matches AC1 in the story file. DO NOT REORDER without updating the
 * story — the grouping is the documentation.
 */
const STORY_1_7C_KEYS = [
  // AppLayout — sidebar + topbar chrome.
  // Story 1d-3 migrated:
  //   app.layout.sidebar.brand          → sidebar.brand
  //   app.layout.sidebar.collapseToggle → sidebar.collapseToggle
  //   app.layout.sidebar.nav.aria       → sidebar.nav.primary
  //   app.layout.topbar.breadcrumb      → topbar.breadcrumb.label
  //   app.layout.topbar.search          → topbar.search.placeholder
  //   app.layout.topbar.searchHint      → topbar.search.hint
  //   app.layout.userPill.roleLabel.*   → userPill.role.*
  // Migrated keys now appear in STORY_1D_3_KEYS below. The keys retained
  // here are still consumed by 1-7c's own surfaces (`AppLayout`, language
  // toggle, sign-out CTA).
  'app.layout.userPill.signOut',
  'app.layout.languageToggle.aria',
  'app.layout.languageToggle.en',
  'app.layout.languageToggle.vi',
  'app.layout.skipToContent',

  // ErrorBoundary — replaces 1-7b's minimal RootErrorBoundary; the
  // `app.errorFallback` key from 1-7b is DELETED in this story.
  'app.errorBoundary.title',
  'app.errorBoundary.body',
  'app.errorBoundary.eventIdLabel',
  'app.errorBoundary.retryCta',
  'app.errorBoundary.homeLinkCta',

  // PermissionDenied — UX-DR16 orientation, two body-copy variants
  'app.permissionDenied.title',
  'app.permissionDenied.bodyOwnerAdmin',
  'app.permissionDenied.bodyOwner',
  'app.permissionDenied.contactLinkCta',
  'app.permissionDenied.homeLinkCta',
  'app.permissionDenied.requiredRoleSummaryOwnerAdmin',
  'app.permissionDenied.requiredRoleSummaryOwner',

  // NotFound — closes 1-7b's W1 catch-all defer
  'app.notFound.title',
  'app.notFound.body',
  'app.notFound.homeLinkCta',

  // Initial auth-screen keys — Stories 1-8 / 1-9a-d will consume; seeded
  // here so the parity helper has coverage and the bilingual smoke spec
  // has surface area for /login.
  'auth.login.title',
  'auth.login.submit',
  'auth.login.googleCta',
  'auth.login.emailCollapse',
  'auth.register.title',
  'auth.register.submit',
  'auth.common.email',
  'auth.common.password',
  'auth.common.passwordToggleAria',
] as const

/**
 * Story 1d-2 — Storybook placeholder keys introduced by AC8. The
 * primitive `*.tsx` files do NOT consume i18n strings (presentational
 * shells); the assertion target is the demo copy rendered inside the
 * `*.stories.tsx` files (toast bodies, command empty-results text,
 * label suffixes, form placeholders, long Vietnamese tooltip / popover
 * fixtures). Per-story discharge of R38 — NOT a separate ATDD ceremony.
 */
const STORY_1D_2_KEYS = [
  'storybook.toast.success',
  'storybook.toast.error',
  'storybook.toast.info',
  'storybook.command.empty',
  'storybook.label.required',
  'storybook.label.optional',
  'storybook.placeholder.email',
  'storybook.placeholder.name',
  'storybook.placeholder.longViText',
  // Code review 2026-06-17 — Form story play asserts locale-correct
  // validation copy. Schema messages and demo labels live as keys so the
  // FormMessage component renders the localized copy in both en + vi.
  'storybook.form.emailInvalid',
  'storybook.form.nameRequired',
  'storybook.form.agreedRequired',
  'storybook.form.emailHelp',
  'storybook.form.nameLabel',
  'storybook.form.agreedLabel',
  // Calendar / Popover / Tooltip — replace hardcoded Vietnamese copy
  // (`buổi học hôm nay`, `Trạng thái`) with keys so the `en` locale renders
  // English content instead of Vietnamese.
  'storybook.calendar.eventToday',
  'storybook.popover.statusTitle',
  'storybook.tooltip.statusTrigger',
  // Input / Textarea — replace `auth.common.email` reuse on non-email
  // labels and the `storybook.placeholder.longViText` reuse as a fake
  // error message.
  'storybook.textarea.label',
  'storybook.textarea.helper',
  'storybook.textarea.errorTooLong',
  'storybook.textarea.readOnlyContents',
  'storybook.input.hoursLabel',
  'storybook.input.hoursHelper',
] as const

describe('Story 1d-2 i18n parity (R38)', () => {
  test('every Story 1d-2 storybook key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1D_2_KEYS)
  })
})

/**
 * Story 1d-3 — app-shell stack keys. Per-story discharge of R38 for the
 * domain components: AppShell, SidebarShell (× 4 role variants),
 * SidebarNavItem, UserPill, TopbarShell, BreadcrumbBar, SearchPill,
 * PageHead, MobileTabBar (× 3 role variants), MobileTab.
 *
 * Grouped by namespace for readability. Namespace coverage is enforced by
 * `scripts/i18n-parity.mjs` — every `sidebar.*` / `topbar.*` /
 * `mobileTab.*` / `pageHead.*` / `userPill.*` / `appShell.*` key MUST
 * appear in some `STORY_1D_*_KEYS` array exported below. An orphan key
 * (in JSON but not enumerated anywhere) fails the script.
 */
export const STORY_1D_3_KEYS = [
  // Sidebar chrome + aria templates
  'sidebar.brand',
  'sidebar.nav.primary',
  'sidebar.nav.unreadAria',
  'sidebar.section.settings',

  // Sidebar — Owner nav
  'sidebar.owner.dashboard',
  'sidebar.owner.people',
  'sidebar.owner.classes',
  'sidebar.owner.schedule',
  'sidebar.owner.analytics',
  'sidebar.owner.inbox',
  'sidebar.owner.knowledgeHub',
  'sidebar.owner.archive',
  'sidebar.owner.settings',

  // Sidebar — Admin nav (Owner MINUS Settings)
  'sidebar.admin.dashboard',
  'sidebar.admin.people',
  'sidebar.admin.classes',
  'sidebar.admin.schedule',
  'sidebar.admin.analytics',
  'sidebar.admin.inbox',
  'sidebar.admin.knowledgeHub',
  'sidebar.admin.archive',

  // Sidebar — Teacher nav
  'sidebar.teacher.dashboard',
  'sidebar.teacher.classes',
  'sidebar.teacher.schedule',
  'sidebar.teacher.exercises',
  'sidebar.teacher.questions',
  'sidebar.teacher.students',
  'sidebar.teacher.analytics',
  'sidebar.teacher.inbox',
  'sidebar.teacher.knowledgeHub',
  'sidebar.teacher.archive',

  // Sidebar — Student nav (student-tone labels)
  'sidebar.student.dashboard',
  'sidebar.student.myClasses',
  'sidebar.student.assignments',
  'sidebar.student.mySchedule',
  'sidebar.student.questions',
  'sidebar.student.myPerformance',
  'sidebar.student.inbox',

  // Topbar
  'topbar.breadcrumb.label',
  'topbar.breadcrumb.more',
  'topbar.search.placeholder',
  'topbar.search.hint',
  'topbar.sidebarToggle.collapse',
  'topbar.sidebarToggle.expand',

  // UserPill role labels
  'userPill.role.owner',
  'userPill.role.admin',
  'userPill.role.teacher',
  'userPill.role.student',

  // MobileTabBar chrome (nav landmark label distinct from desktop sidebar's)
  'mobileTab.nav.primary',
  'mobileTab.unreadAria',

  // MobileTabBar — Student tabs (per IA `s74–s81`)
  'mobileTab.student.home',
  'mobileTab.student.assignments',
  'mobileTab.student.inbox',
  'mobileTab.student.classes',
  'mobileTab.student.me',

  // MobileTabBar — Teacher tabs (per IA `s82–s85`)
  'mobileTab.teacher.home',
  'mobileTab.teacher.classes',
  'mobileTab.teacher.inbox',
  'mobileTab.teacher.schedule',
  'mobileTab.teacher.me',

  // MobileTabBar — Owner tabs (extrapolated; per `s86`)
  'mobileTab.owner.home',
  'mobileTab.owner.people',
  'mobileTab.owner.inbox',
  'mobileTab.owner.analytics',
  'mobileTab.owner.me',

  // PageHead fixture (storybook demo only)
  'pageHead.fixture.title',
  'pageHead.fixture.subtitle',
] as const

describe('Story 1d-3 i18n parity (R38)', () => {
  test('every Story 1d-3 key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1D_3_KEYS)
  })
})

/**
 * Story 1d-4 — Phase 4 visual bridge keys. Per-story discharge of R38
 * for the static visual shells: WriteDocSurface, CommentCard,
 * WritingGradingSurface, SpeakingGradingSurface, AnchoredQuestionCard,
 * MobileWritingSurface, InboxRow, InboxListShell, ScopeBar,
 * AnalyticsHomeShell. None of these namespaces are under the
 * `COVERED_NAMESPACES` enforcement (sidebar / topbar / mobileTab /
 * pageHead / userPill / appShell), so the orphan-key script does NOT
 * gate them — this block is the per-story traceability discharge so a
 * 1d-4 audit can grep the list of new keys in one place.
 */
export const STORY_1D_4_KEYS = [
  // Shared criterion labels (writing + speaking band breakdowns)
  'criterion.taskAchievement',
  'criterion.coherenceCohesion',
  'criterion.lexicalResource',
  'criterion.grammar',
  'criterion.fluency',
  'criterion.lexical',
  'criterion.pronunciation',

  // WriteDocSurface (AC1)
  'writeDocSurface.regionLabel',
  'writeDocSurface.titlePlaceholder',
  'writeDocSurface.toolbar.label',
  'writeDocSurface.toolbar.bold',
  'writeDocSurface.toolbar.italic',
  'writeDocSurface.toolbar.heading',
  'writeDocSurface.toolbar.list',
  'writeDocSurface.save.saved',
  'writeDocSurface.save.saving',
  'writeDocSurface.save.offline',
  'writeDocSurface.save.error',
  'writeDocSurface.footer.wordCount_one',
  'writeDocSurface.footer.wordCount_other',
  'writeDocSurface.footer.timeOnTask',

  // CommentCard (shared by AC2 + AC3)
  'commentCard.action.resolve',
  'commentCard.action.reopen',
  'commentCard.action.edit',

  // WritingGradingSurface (AC2)
  'writingGrading.regionLabel',
  'writingGrading.score.label',
  'writingGrading.essay.label',
  'writingGrading.rail.label',
  'writingGrading.rail.empty',
  'writingGrading.action.submit',
  'writingGrading.action.saveDraft',

  // SpeakingGradingSurface (AC3)
  'speakingGrading.regionLabel',
  'speakingGrading.score.label',
  'speakingGrading.action.play',
  'speakingGrading.waveform.label',
  'speakingGrading.waveform.noRecording',
  'speakingGrading.rail.label',
  'speakingGrading.rail.empty',

  // AnchoredQuestionCard (AC4)
  'anchoredQuestion.replyInput.label',
  'anchoredQuestion.replyInput.placeholder',
  'anchoredQuestion.action.aiSuggest',
  'anchoredQuestion.action.submitReply',
  'anchoredQuestion.student.awaiting',

  // MobileWritingSurface (AC5)
  'mobileWriting.regionLabel',
  'mobileWriting.titlePlaceholder',
  'mobileWriting.action.back',
  'mobileWriting.toolbar.label',
  'mobileWriting.toolbar.bold',
  'mobileWriting.toolbar.italic',
  'mobileWriting.toolbar.heading',
  'mobileWriting.toolbar.list',
  'mobileWriting.save.saved',
  'mobileWriting.save.saving',
  'mobileWriting.save.offline',
  'mobileWriting.save.error',
  'mobileWriting.footer.wordCount_one',
  'mobileWriting.footer.wordCount_other',

  // InboxRow + InboxListShell (AC6)
  'inboxRow.unread.aria',
  'inboxRow.action.reply',
  'inboxRow.action.grade',
  'inboxRow.action.view',
  'inboxRow.action.open',
  'inboxRow.action.review',
  'inboxRow.action.archive',
  'inboxRow.teacher.question.main',
  'inboxRow.teacher.submission.main',
  'inboxRow.teacher.mention.main',
  'inboxRow.student.reply.main',
  'inboxRow.student.grade.main',
  'inboxRow.student.assignment.main',
  'inboxRow.student.schedule.main',
  'inboxRow.student.mention.main',
  'inboxRow.admin.enrolment.main',
  'inboxRow.admin.staff.main',
  'inboxRow.admin.billing.main',
  'inboxRow.admin.integration.main',
  'inboxRow.billingStatus.succeeded',
  'inboxRow.billingStatus.failed',
  'inboxRow.integrationAction.connected',
  'inboxRow.meta.classTime',
  'inboxRow.meta.time',
  'inboxList.regionLabel',
  'inboxList.filters.label',
  'inboxList.filters.remove',
  'inboxList.rows.label',
  'inboxList.empty',
  'inboxList.filter.all',
  'inboxList.filter.questions',
  'inboxList.filter.submissions',
  'inboxList.filter.mentions',
  'inboxList.filter.replies',
  'inboxList.filter.grades',
  'inboxList.filter.assignments',
  'inboxList.filter.enrolments',
  'inboxList.filter.staff',
  'inboxList.filter.billing',
  'inboxList.filter.integrations',

  // ScopeBar + AnalyticsHomeShell (AC7)
  'scopeBar.label',
  'scopeBar.scope.label',
  'scopeBar.scope.mine',
  'scopeBar.scope.all',
  'scopeBar.scope.centerWide',
  'scopeBar.classPicker.label',
  'scopeBar.classPicker.placeholder',
  'scopeBar.classPicker.noOptions',
  'scopeBar.dateRange.label',
  'scopeBar.dateRange.aria',
  'analyticsHome.title.teacher',
  'analyticsHome.title.admin',
  'analyticsHome.title.owner',
  'analyticsHome.subtitle.teacher',
  'analyticsHome.subtitle.admin',
  'analyticsHome.subtitle.owner',
  'analyticsHome.classOption.ielts65SecA',
  'analyticsHome.classOption.ielts65SecB',
  'analyticsHome.classOption.ielts70SecA',
  'analyticsHome.classOption.ielts70SecB',
  'analyticsHome.classOption.ielts60SecC',
] as const

describe('Story 1d-4 i18n parity (R38)', () => {
  test('every Story 1d-4 key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1D_4_KEYS)
  })
})

/**
 * Story 1-8 — auth UI registration + login. Per-story discharge of R38
 * for the polished /register and /login surfaces + the five shared
 * components in `src/features/auth/components/`. The 1-7c-seeded keys
 * (auth.login.title / auth.login.submit / auth.login.googleCta /
 * auth.login.emailCollapse / auth.register.title / auth.register.submit /
 * auth.common.email / auth.common.password / auth.common.passwordToggleAria)
 * stay in STORY_1_7C_KEYS — this block ONLY enumerates the keys added
 * by Story 1-8.
 *
 * Four ★ REVIEWER-MANDATORY keys (login error variants + oauthGeneric)
 * must get a Vietnamese-fluent reviewer pass before merge — see story
 * AC2 for the contract.
 */
export const STORY_1_8_KEYS = [
  // Register-screen Google + email collapse copy
  'auth.register.googleCta',
  'auth.register.emailCollapse',

  // Register form fields + cross-screen link + terms
  'auth.register.fullName',
  'auth.register.fullNamePlaceholder',
  'auth.register.signInLink',
  'auth.register.terms',

  // Login-only copy that pairs with the register additions above
  'auth.login.signUpLink',
  'auth.login.rememberMe',
  'auth.login.forgotPassword',

  // Shared auth-form chrome (divider + placeholders)
  'auth.common.dividerOr',
  'auth.common.emailPlaceholder',
  'auth.common.passwordPlaceholder',
  'auth.common.loginPasswordPlaceholder',

  // PasswordStrengthBar aria-live announcement keys (5 levels per UX-DR8;
  // `empty` is the no-input baseline so the helper has full coverage even
  // when the visual bar renders nothing)
  'auth.common.passwordStrength.empty',
  'auth.common.passwordStrength.weak',
  'auth.common.passwordStrength.fair',
  'auth.common.passwordStrength.strong',
  'auth.common.passwordStrength.veryStrong',

  // Field-level validation messages (consumed by useRegisterSchema +
  // useLoginSchema builder hooks; login uses passwordRequired, register
  // uses passwordMin per AC4 schema rationale — never leak min-length on
  // login per SEC-1). passwordMax / fullNameMax / passwordNotBlank land
  // with code-review P9 + P10 (2026-06-25) so localized copy reaches the
  // vi locale on the rare max-length and all-whitespace hits.
  'auth.common.validation.emailRequired',
  'auth.common.validation.emailFormat',
  'auth.common.validation.passwordMin',
  'auth.common.validation.passwordMax',
  'auth.common.validation.passwordRequired',
  'auth.common.validation.passwordNotBlank',
  'auth.common.validation.fullNameRequired',
  'auth.common.validation.fullNameMax',

  // Register-screen error envelopes (409 / 429 / generic / email-delivery)
  'auth.register.error.emailTaken',
  'auth.register.error.rateLimited',
  'auth.register.error.generic',
  'auth.register.emailDelivery.failedToast',

  // Login-screen error envelopes — accountLocked / rateLimited / generic /
  // oauthGeneric are the 4 ★ REVIEWER-MANDATORY keys
  'auth.login.error.invalidCredentials',
  'auth.login.error.accountLocked',
  'auth.login.error.rateLimited',
  'auth.login.error.generic',
  'auth.login.error.oauthGeneric',
] as const

describe('Story 1-8 i18n parity (R38)', () => {
  test('every Story 1-8 key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1_8_KEYS)
  })
})

/**
 * Story 1-9a — email verification UI keys. Per-story discharge of R38
 * for the polished /verify-email surface + the LoginPage success banner.
 *
 * 5 ★ REVIEWER-MANDATORY Vietnamese keys (flagged in the story AC2):
 *   - auth.verify.resendSentToast
 *   - auth.verify.spamHint
 *   - auth.verify.googleFallbackCta (also gated by Winston architecture
 *     confirmation that Google OAuth auto-links same-email accounts)
 *   - auth.verify.expiredBody
 *   - auth.verify.error.generic
 *
 * The LoginPage banner key (auth.login.banner.verified) lives outside the
 * auth.verify.* namespace because the success banner is shown on the
 * /login surface, not the /verify-email surface — see story AC6.
 */
export const STORY_1_9A_KEYS = [
  // Polling-mode envelope screen (AC3)
  'auth.verify.title',
  'auth.verify.bodyPrefix',
  'auth.verify.bodySuffix',
  'auth.verify.resendCta',
  'auth.verify.resendCountdown',
  'auth.verify.resendSentToast',
  'auth.verify.spamHint',
  'auth.verify.wrongEmailPrompt',
  'auth.verify.wrongEmailCta',
  'auth.verify.googleFallbackPrompt',
  'auth.verify.googleFallbackCta',

  // 10-minute polling cap + manual recheck (AC5)
  'auth.verify.timeoutHeading',
  'auth.verify.timeoutBody',
  'auth.verify.recheckCta',

  // Expired state — 404 polling result + 410 click-through (AC5b)
  'auth.verify.expiredHeading',
  'auth.verify.expiredBody',
  'auth.verify.expiredResendCta',

  // Invalid state — neither query param + 404 click-through (AC7)
  'auth.verify.invalidHeading',
  'auth.verify.invalidBody',

  // Error envelopes — 422 / 5xx / network + 429 (AC4 + AC6)
  'auth.verify.error.generic',
  'auth.verify.error.rateLimited',

  // Click-through transient announcements (AC6)
  'auth.verify.checkingNow',
  'auth.verify.successRedirecting',

  // LoginPage success banner — the post-verify landing on /login?verified=1 (AC6)
  'auth.login.banner.verified',
] as const

describe('Story 1-9a i18n parity (R38)', () => {
  test('every Story 1-9a key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1_9A_KEYS)
  })
})

/**
 * Story 1-9b — password reset UI keys. Per-story discharge of R38 for the
 * new /forgot-password and /reset-password surfaces + the LoginPage
 * `?reset=1` success banner.
 *
 * 4 ★ REVIEWER-MANDATORY Vietnamese keys (flagged in story AC2 for
 * VN-fluent reviewer pass before merge):
 *   - auth.forgotPassword.sentBody (Sally rewrite — lead-with-action)
 *   - auth.forgotPassword.error.generic
 *   - auth.resetPassword.body (Sally — "chưa từng dùng" native phrasing)
 *   - auth.login.banner.reset (Sally — active voice replaces passive-victim)
 *
 * Pragmatic-scope deviation (Winston framing fix 2026-06-26): the Epic 1c
 * AC for "pre-fill email on expired-CTA" is rejected on security grounds
 * (anti-enum attack surface + email leak via preview tooling). John has
 * filed an Epic AC amendment removing the requirement; no `auth.resetPassword.expiredCta.prefilledEmail`
 * key is added.
 */
export const STORY_1_9B_KEYS = [
  // ForgotPasswordPage form mode (AC3)
  'auth.forgotPassword.title',
  'auth.forgotPassword.body',
  'auth.forgotPassword.emailLabel',
  'auth.forgotPassword.submit',

  // ForgotPasswordPage anti-enum confirmation mode (AC3 + Sally typo-escape addition)
  'auth.forgotPassword.sentHeading',
  'auth.forgotPassword.sentBody',
  'auth.forgotPassword.spamHint',
  'auth.forgotPassword.wrongEmail',
  'auth.forgotPassword.resendCta',
  'auth.forgotPassword.resendCountdown',

  // ForgotPasswordPage footer
  'auth.forgotPassword.backToLogin',

  // ForgotPasswordPage error envelopes (AC4 — 429 / 422 / 5xx)
  'auth.forgotPassword.error.rateLimited',
  'auth.forgotPassword.error.generic',

  // ResetPasswordPage form mode (AC5)
  'auth.resetPassword.title',
  'auth.resetPassword.body',
  'auth.resetPassword.newPasswordLabel',
  'auth.resetPassword.confirmPasswordLabel',
  'auth.resetPassword.submit',

  // ResetPasswordPage 410 expired state (AC6 — UX-DR16 three-part)
  'auth.resetPassword.expiredHeading',
  'auth.resetPassword.expiredBody',
  'auth.resetPassword.expiredCta',

  // ResetPasswordPage 409 consumed state (AC6)
  'auth.resetPassword.consumedHeading',
  'auth.resetPassword.consumedBody',
  // Added [Review][Patch] P10 — code-review 2026-06-26 — consumed-state
  // secondary CTA copy that doesn't imply the prior reset failed.
  'auth.resetPassword.consumedForgotCta',

  // ResetPasswordPage 404 / no-token invalid state (AC6 — DRY)
  'auth.resetPassword.invalidHeading',
  'auth.resetPassword.invalidBody',

  // ResetPasswordPage error envelopes (AC5 refine + AC6 422 / 5xx)
  'auth.resetPassword.error.passwordMismatch',
  'auth.resetPassword.error.generic',

  // LoginPage success banner — `/login?reset=1` landing (AC7)
  'auth.login.banner.reset',
] as const

describe('Story 1-9b i18n parity (R38)', () => {
  test('every Story 1-9b key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1_9B_KEYS)
  })
})

/**
 * Story 1-9c — invite acceptance UI keys. Per-story discharge of R38 for the
 * new `/invite/:token` surface + the LoginPage `?invited=true` success banner.
 *
 * 7 ★ REVIEWER-MANDATORY Vietnamese keys (flagged in story AC3 for VN-fluent
 * reviewer pass before merge):
 *   - auth.invite.title (active-voice rewrite per Sally party-mode 2026-06-26)
 *   - auth.invite.titleWithCenter (Vietnamese interpolation order)
 *   - auth.invite.error.expired.body (centerName + inviterEmail interpolation)
 *   - auth.invite.error.emailMismatch.body (privacy-aware copy — no echo)
 *   - auth.invite.error.emailAlreadyRegistered.body
 *   - auth.invite.error.passwordNotAllowed.body (one to watch)
 *   - auth.login.banner.invited (active-voice rewrite — drops awkward em-dash)
 */
export const STORY_1_9C_KEYS = [
  // Header + body copy (AC4)
  'auth.invite.title',
  'auth.invite.titleWithCenter',
  'auth.invite.body',

  // Primary actions (AC4)
  'auth.invite.googleCta',
  'auth.invite.emailCollapse',
  'auth.invite.emailFormExpandedAnnouncement',
  'auth.invite.fullNameLabel',
  'auth.invite.passwordLabel',
  'auth.invite.submit',
  'auth.invite.backToLogin',

  // Terminal error states (AC5) — 404 / 410 / 409 / 400 / 422 / 5xx / 429
  'auth.invite.error.notFound.heading',
  'auth.invite.error.notFound.body',
  'auth.invite.error.expired.heading',
  'auth.invite.error.expired.body',
  'auth.invite.error.expired.contactCta',
  'auth.invite.error.alreadyAccepted.heading',
  'auth.invite.error.alreadyAccepted.body',
  'auth.invite.error.alreadyAccepted.cta',
  'auth.invite.error.emailMismatch.heading',
  'auth.invite.error.emailMismatch.body',
  'auth.invite.error.passwordNotAllowed.heading',
  'auth.invite.error.passwordNotAllowed.body',
  'auth.invite.error.invalidToken.heading',
  'auth.invite.error.invalidToken.body',
  'auth.invite.error.emailAlreadyRegistered.heading',
  'auth.invite.error.emailAlreadyRegistered.body',
  'auth.invite.error.emailAlreadyRegistered.cta',
  'auth.invite.error.rateLimited',
  'auth.invite.error.generic',

  // Client-side validation (AC4)
  'auth.invite.error.fullNameRequired',

  // LoginPage success banner — `/login?invited=true` landing (AC6)
  'auth.login.banner.invited',
] as const

describe('Story 1-9c i18n parity (R38)', () => {
  test('every Story 1-9c key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1_9C_KEYS)
  })
})

/**
 * Story 1-9d — Auth Error & Recovery States.
 *
 * 16 keys cover the four new states (Lockout, OAuth Email Mismatch, Workspace
 * Blocked, Session Expiry) per AC1–AC4. Forked body copy on the Workspace
 * Blocked screen (Sally STRONG fork — bodyUserinfoFailed vs bodyEmailUnverified)
 * and the threshold-announce a11y pin (60s + 30s thresholds) are reflected
 * in the key list below.
 *
 * 6 ★ REVIEWER-MANDATORY Vietnamese keys (flagged in story AC6 for VN-fluent
 * reviewer pass before merge):
 *   - auth.login.lockout.heading ("Vui lòng" register edit — apology framing)
 *   - auth.login.oauthMismatch.body (privacy-aware, no email echo)
 *   - auth.login.workspaceBlocked.bodyUserinfoFailed (Workspace-policy framing)
 *   - auth.login.workspaceBlocked.bodyEmailUnverified (forced-verification framing)
 *   - auth.login.banner.sessionExpired ("vì lý do an toàn" — reassuring tone)
 *   - auth.login.banner.sessionExpiredDataLossHint (honest framing about lost work)
 */
export const STORY_1_9D_KEYS = [
  // Lockout state (AC1) — 6 keys (body has _one/_other plural pair — code review P4)
  'auth.login.lockout.heading',
  'auth.login.lockout.body_one',
  'auth.login.lockout.body_other',
  'auth.login.lockout.thresholdOneMinute',
  'auth.login.lockout.thresholdThirtySeconds',
  'auth.login.lockout.resetCta',

  // OAuth Email Mismatch (AC2) — 4 keys
  'auth.login.oauthMismatch.heading',
  'auth.login.oauthMismatch.body',
  'auth.login.oauthMismatch.reopenInviteHint',
  'auth.login.oauthMismatch.retryGoogleCta',

  // Workspace Blocked (AC3) — 5 keys (shared heading + forked body + 2 CTAs)
  'auth.login.workspaceBlocked.heading',
  'auth.login.workspaceBlocked.bodyUserinfoFailed',
  'auth.login.workspaceBlocked.bodyEmailUnverified',
  'auth.login.workspaceBlocked.tryPersonalCta',
  'auth.login.workspaceBlocked.registerCta',

  // Session Expiry banner (AC4) — 2 keys
  'auth.login.banner.sessionExpired',
  'auth.login.banner.sessionExpiredDataLossHint',
] as const

describe('Story 1-9d i18n parity (R38)', () => {
  test('every Story 1-9d key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1_9D_KEYS)
  })
})

/**
 * Story 1-9d STORY_1_9D_KEYS closed enumeration (Murat M7 pin — R-NEW=16
 * orphan-key misattribution defense).
 *
 * Catches at test-time the case where a dev claims an orphan key from a
 * prior story (e.g. `auth.login.error.invalidCredentials`, shipped 1-8)
 * into STORY_1_9D_KEYS — per-key parity stays green but the historical
 * lineage becomes a lie. Same shape as the COVERED_NAMESPACES script-level
 * ratchet, scoped to the new story's array.
 */
describe('Story 1-9d STORY_1_9D_KEYS closed enumeration (R-NEW=16)', () => {
  const ALLOWED_PREFIXES = [
    'auth.login.lockout.',
    'auth.login.oauthMismatch.',
    'auth.login.workspaceBlocked.',
  ] as const
  const ALLOWED_EXACT = [
    'auth.login.banner.sessionExpired',
    'auth.login.banner.sessionExpiredDataLossHint',
  ] as const

  test.each(STORY_1_9D_KEYS)(
    '%s belongs to a 1-9d allowed prefix or exact key',
    (key) => {
      const ok =
        ALLOWED_PREFIXES.some((p) => key.startsWith(p)) ||
        (ALLOWED_EXACT as readonly string[]).includes(key)
      expect(ok).toBe(true)
    },
  )
})

describe('Story 1-7c i18n parity (R38)', () => {
  test('every Story 1-7c i18n key exists in both en.json and vi.json', () => {
    // Will throw with a readable diff naming each missing key per locale
    // until Task 1.2 / 1.3 add them. The assertion is intentionally
    // single-shot — one failure surfaces the entire missing-key list so
    // the dev can fix in one pass.
    assertI18nParity(STORY_1_7C_KEYS)
  })

  test('legacy 1-7b key app.errorFallback is REMOVED from both locales', () => {
    // Story 1-7c deletes `app.errorFallback` because the polished
    // ErrorBoundary uses `app.errorBoundary.*` instead. If this assertion
    // fails GREEN (key exists), Task 1.6 was skipped — the polished
    // boundary works AND the old key sits unreferenced.
    expect(() => assertI18nParity(['app.errorFallback'])).toThrow(
      /i18n parity check failed/,
    )
  })
})

/**
 * Story 2-3a — onboarding wizard (persona pick + center setup).
 *
 * Closed-enumeration STORY_2_3A_KEYS mirrors the 1-9d precedent — every new
 * key gets a `describe.each` ratchet claiming an allowed prefix so a future
 * orphan under `onboarding.` OR `dashboard.welcomeBack.` fails CI. Also
 * exercises `assertI18nInterpolationParity` (Murat-S2 fold) so a Vietnamese
 * translator can't rename `{{seconds}}` → `{{giay}}` without CI catching it.
 *
 * Story 2-4 AC13 atomic rename: the 3 originally-shipped
 * `dashboard.finishSetup.*` keys are reparented to `dashboard.welcomeBack.*`
 * (see STORY_2_4_KEYS block below). Both STORY_2_3A_KEYS and STORY_2_4_KEYS
 * list them — the 2-3a block claims them as its historical debt, the 2-4
 * block claims them as its ongoing prefix ratchet.
 */
export const STORY_2_3A_KEYS = [
  'onboarding.wizard.brand',
  'onboarding.wizard.signOut',
  'onboarding.wizard.autoSaving.idle',
  'onboarding.wizard.autoSaving.saved',
  'onboarding.wizard.autoSaving.saving',
  'onboarding.wizard.autoSaving.failed',
  'onboarding.wizard.autoSaving.failedPersistent',
  'onboarding.wizard.saveAndFinishLater',
  'onboarding.persona.eyebrow',
  'onboarding.persona.title',
  'onboarding.persona.subtitle',
  'onboarding.persona.operator.title',
  'onboarding.persona.operator.lede',
  'onboarding.persona.operator.description',
  'onboarding.persona.founder.title',
  'onboarding.persona.founder.lede',
  'onboarding.persona.founder.description',
  'onboarding.persona.solo.title',
  'onboarding.persona.solo.lede',
  'onboarding.persona.solo.description',
  'onboarding.persona.continueCta',
  'onboarding.persona.error.rateLimited',
  'onboarding.persona.error.emailVerificationRequired',
  'onboarding.persona.error.generic',
  'onboarding.center.step',
  'onboarding.center.title',
  'onboarding.center.subtitle',
  'onboarding.center.form.nameLabel',
  'onboarding.center.form.namePlaceholder',
  'onboarding.center.form.shortCodePreviewLabel',
  'onboarding.center.form.shortCodeCaveat',
  'onboarding.center.form.shortCodeFallback',
  'onboarding.center.form.brandingLabel',
  'onboarding.center.form.uploadLogoCaption',
  'onboarding.center.form.saveContinueCta',
  'onboarding.center.form.backCta',
  'onboarding.center.form.nextCaption',
  'onboarding.center.error.nameRequired',
  'onboarding.center.error.nameMax',
  'onboarding.center.error.nameInvalid',
  'onboarding.center.error.userAlreadyHasCenter',
  'onboarding.center.error.userAlreadyHasCenter.hint',
  'onboarding.center.error.emailVerificationRequired',
  'onboarding.center.error.rateLimited',
  'onboarding.center.error.generic',
  'onboarding.center.form.branchesCaption',
  'onboarding.center.form.brandColor.deepNavy',
  'onboarding.center.form.brandColor.amber',
  'onboarding.center.form.brandColor.green',
  'onboarding.center.form.brandColor.red',
  'onboarding.center.form.brandColor.brown',
  'onboarding.center.form.brandColor.gray',
  // R1 code-review additions.
  'onboarding.wizard.autoSaving.savedAnnouncement',
  'onboarding.wizard.autoSaving.retryNow',
  'onboarding.persona.error.retryCta',
  'onboarding.center.error.userAlreadyHasCenterGeneric',
  'onboarding.center.error.brandColorInvalid',
  // Story 2-4 AC13 4-file atomic rename: `dashboard.finishSetup.*` renamed
  // to `dashboard.welcomeBack.*` (also enumerated in STORY_2_4_KEYS).
  'dashboard.welcomeBack.banner',
  'dashboard.welcomeBack.continueCta',
  'dashboard.welcomeBack.awaitingNextStep',
] as const

describe('Story 2-3a i18n parity (R38)', () => {
  test('every Story 2-3a i18n key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_2_3A_KEYS)
  })

  test('interpolation-token parity holds across en / vi for every 2-3a key (Murat-S2)', () => {
    assertI18nInterpolationParity(STORY_2_3A_KEYS)
  })

  const ALLOWED_PREFIXES = ['onboarding.', 'dashboard.welcomeBack.'] as const

  test.each(STORY_2_3A_KEYS)(
    '%s belongs to a 2-3a allowed prefix',
    (key) => {
      const ok = ALLOWED_PREFIXES.some((p) => key.startsWith(p))
      expect(ok).toBe(true)
    },
  )
})

/**
 * Story 2-3b — onboarding wizard (template pick + class spawn + Solo first
 * class).
 *
 * Closed-enumeration STORY_2_3B_KEYS + prefix-ratchet block mirrors the
 * 2-3a precedent. Every new key added by this story lands in this array so
 * a future orphan under `onboarding.template.*`, `onboarding.spawn.*`,
 * `onboarding.solo.*`, or `onboarding.wizard.*` fails CI.
 *
 * Prefix ratchet allows: onboarding.template.* / onboarding.spawn.* /
 * onboarding.solo.* / onboarding.wizard.* / dashboard.welcomeBack.*
 * (Murat-S1 fold; 2-4 AC13 rename from `dashboard.finishSetup.*`).
 *
 * Interpolation tokens (Murat-S2, 10 total):
 *   {{index}} {{seconds}} {{n}} {{max}} {{userFullName}}
 *   {{templateName}} {{band}} {{name}} {{role}} {{requestId}}
 */
export const STORY_2_3B_KEYS = [
  'onboarding.template.eyebrow',
  'onboarding.template.title',
  'onboarding.template.subtitle',
  'onboarding.template.buildFromScratch.title',
  'onboarding.template.buildFromScratch.description',
  'onboarding.template.card.systemBadge',
  'onboarding.template.card.centerBadge',
  'onboarding.template.card.targetBand',
  'onboarding.template.card.sessions',
  'onboarding.template.skill.writing',
  'onboarding.template.skill.speaking',
  'onboarding.template.skill.listening',
  'onboarding.template.skill.reading',
  'onboarding.template.skill.listening_reading',
  'onboarding.template.skill.all_skills',
  'onboarding.template.preview.title',
  'onboarding.template.preview.sessionsPreview',
  'onboarding.template.continueCta',
  'onboarding.template.error.generic',
  'onboarding.template.error.seedIncomplete',
  'onboarding.template.error.retryCta',
  'onboarding.spawn.eyebrow',
  'onboarding.spawn.title',
  'onboarding.spawn.subtitle',
  'onboarding.spawn.rowHeadingAria',
  'onboarding.spawn.rowIndex',
  'onboarding.spawn.cohortName.label',
  'onboarding.spawn.cohortName.placeholder',
  'onboarding.spawn.startDate.label',
  'onboarding.spawn.teacher.label',
  'onboarding.spawn.teacher.empty',
  'onboarding.spawn.teacher.assigned',
  'onboarding.spawn.teacher.invitedPending',
  'onboarding.spawn.teacher.founderAutoAssign',
  'onboarding.spawn.teacher.selfInviteHintV1',
  'onboarding.spawn.teacher.composerTitle',
  'onboarding.spawn.teacher.composerEmailLabel',
  'onboarding.spawn.teacher.composerNameLabel',
  'onboarding.spawn.teacher.composerAddCta',
  'onboarding.spawn.teacher.composerCancelCta',
  'onboarding.spawn.rowMinimum',
  'onboarding.spawn.deleteClassAria',
  'onboarding.spawn.addClassCta',
  'onboarding.spawn.saveAndSpawnCta',
  'onboarding.spawn.saveAndSpawnCta.pending',
  'onboarding.spawn.customTemplateNotice',
  'onboarding.spawn.customTemplateNotice.pickInstead',
  'onboarding.spawn.pickTemplateInsteadCta',
  'onboarding.spawn.error.cohortRequired',
  'onboarding.spawn.error.cohortMax',
  'onboarding.spawn.error.startDateInvalid',
  'onboarding.spawn.error.startDatePast',
  'onboarding.spawn.error.startDateTooFarFuture',
  'onboarding.spawn.teacher.clearAriaLabel',
  'onboarding.spawn.error.teacherEmailInvalid',
  'onboarding.spawn.error.teacherEmailSelfInvite',
  'onboarding.spawn.error.templateNotFound',
  'onboarding.spawn.error.templateNotFoundToast',
  'onboarding.spawn.error.centerRequiredToast',
  'onboarding.spawn.error.rateLimited',
  'onboarding.spawn.error.generic',
  'onboarding.spawn.error.retryCta',
  'onboarding.spawn.error.autoSaveWarning',
  'onboarding.wizard.resumedFromDraft',
  'onboarding.solo.eyebrow',
  'onboarding.solo.title',
  'onboarding.solo.subtitle',
  'onboarding.solo.teacher.locked',
  'onboarding.solo.teacher.helper',
  'onboarding.solo.templatePickDetails',
  'onboarding.solo.saveAndSpawnCta',
] as const

describe('Story 2-3b i18n parity (R38)', () => {
  test('every Story 2-3b i18n key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_2_3B_KEYS)
  })

  test('interpolation-token parity holds across en / vi for every 2-3b key (Murat-S2)', () => {
    assertI18nInterpolationParity(STORY_2_3B_KEYS)
  })

  const ALLOWED_PREFIXES_2_3B = [
    'onboarding.template.',
    'onboarding.spawn.',
    'onboarding.solo.',
    'onboarding.wizard.',
    'dashboard.welcomeBack.', // 2-4 AC13 rename from `dashboard.finishSetup.`
  ] as const

  test.each(STORY_2_3B_KEYS)(
    '%s belongs to a 2-3b allowed prefix (Murat-S1 ratchet)',
    (key) => {
      const ok = ALLOWED_PREFIXES_2_3B.some((p) => key.startsWith(p))
      expect(ok).toBe(true)
    },
  )
})

/**
 * Story 2-3c — onboarding wizard closer (`/setup/done` celebration screen).
 *
 * Closed-enumeration STORY_2_3C_KEYS + prefix-ratchet block mirrors the
 * 2-3a / 2-3b precedent. Every NEW key added by this story lands in this
 * array — `onboarding.wizard.saveAndFinishLater` (2-3a) is REUSED, not
 * duplicated, so it is NOT in this set.
 *
 * Prefix ratchet: single allow-list `onboarding.done.*` per A-I3 (tighter
 * than the story's initial `['onboarding.done.', 'onboarding.wizard.']`
 * sketch — `wizard.*` is 2-3a's turf, not 2-3c's).
 *
 * Interpolation tokens (M-B1 + A-B2, 3 total):
 *   {{centerName}} {{count}} {{requestId}}
 * ({{shortCode}} is composed via JS template literal in the tile
 * component, NOT via i18next interpolation.)
 */
export const STORY_2_3C_KEYS = [
  'onboarding.done.title',
  'onboarding.done.subtitle.operator',
  'onboarding.done.subtitle.founder',
  'onboarding.done.subtitle.solo_teacher',
  'onboarding.done.stat.classesReady',
  'onboarding.done.stat.classesReady_one',
  'onboarding.done.stat.classesReadyLabel',
  'onboarding.done.stat.teachersInvited',
  'onboarding.done.stat.teachersInvited_one',
  'onboarding.done.stat.teachersInvitedLabel',
  'onboarding.done.stat.subdomain',
  'onboarding.done.openDashboardCta',
  'onboarding.done.error.generic',
  'onboarding.done.error.genericWithRequestId',
  'onboarding.done.error.retryCta',
  'onboarding.done.error.setupIncomplete',
  'onboarding.done.error.continueToDashboardCta',
] as const

describe('Story 2-3c i18n parity (R38)', () => {
  test('every Story 2-3c i18n key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_2_3C_KEYS)
  })

  test('interpolation-token parity holds across en / vi for every 2-3c key (M-B1 + A-B2)', () => {
    assertI18nInterpolationParity(STORY_2_3C_KEYS)
  })

  const ALLOWED_PREFIXES_2_3C = ['onboarding.done.'] as const

  test.each(STORY_2_3C_KEYS)(
    '%s belongs to a 2-3c allowed prefix (A-I3 single-prefix ratchet)',
    (key) => {
      const ok = ALLOWED_PREFIXES_2_3C.some((p) => key.startsWith(p))
      expect(ok).toBe(true)
    },
  )
})

/**
 * Closed-enumeration STORY_2_4_KEYS + prefix-ratchet block mirrors the
 * 2-3c precedent. Story 2-4 owns the post-onboarding checklist card + first
 * AI grade card + sample owner preview + Your Classes row on `/dashboard`.
 *
 * Prefix ratchet: 6-prefix allow-list per AC13 —
 *   `dashboard.welcomeHeading` | `dashboard.welcomeBack.` | `dashboard.checklist.`
 *   | `dashboard.aiSample.` | `dashboard.samplePreview.` | `dashboard.yourClasses.`
 *   | `dashboard.deadLink.`
 *
 * Interpolation tokens covered (`assertI18nInterpolationParity` over ALL 42
 * keys per M-BLOCKER-5): `{{name}}`, `{{completed}}`, `{{total}}`,
 * `{{centerName}}`, `{{epicNum}}`. Additional tokens hidden in Vietnamese
 * variants are surfaced by the helper's per-key token-set comparison.
 *
 * AC13 atomic-commit contract: the 3 shipped `dashboard.finishSetup.*`
 * keys are RENAMED to `dashboard.welcomeBack.*` in the same commit as
 * `TeacherDashboard.tsx`'s 3 `t()` sites + `STORY_2_3A_KEYS` array
 * (lines 864-866) + `ALLOWED_PREFIXES` (line 878) + JSDoc (line 801) +
 * `STORY_2_3B_KEYS` ALLOWED_PREFIXES_2_3B (line 994). This file is one
 * of the 4 files that MUST land atomically.
 *
 * RED-PHASE contract (post `/bmad-tea AT 2-4`):
 *   All 42 keys below are missing from en.json + vi.json until Amelia
 *   lands Task 8.1 (add keys) + Task 6.5 (delete + rename shipped keys).
 *   `npm run i18n-parity` reports 42 missing keys per locale at first run.
 *
 * Note: This block is NOT hoisted above the 2-3a/2-3b/2-3c blocks — those
 * blocks reference `dashboard.finishSetup.*` in their ALLOWED_PREFIXES arrays.
 * The 4-file atomic commit renames those references simultaneously.
 */
export const STORY_2_4_KEYS = [
  // welcome heading (1)
  'dashboard.welcomeHeading',
  // checklist header + copy (10)
  'dashboard.checklist.eyebrow',
  'dashboard.checklist.title.operator',
  'dashboard.checklist.title.founder',
  'dashboard.checklist.title.solo_teacher',
  'dashboard.checklist.subtitle.operator',
  'dashboard.checklist.subtitle.founder',
  'dashboard.checklist.subtitle.solo_teacher',
  'dashboard.checklist.fractionAriaLabel',
  'dashboard.checklist.snoozeCta',
  'dashboard.checklist.footer.autosave',
  // checklist item names (8 — per AC3 mockup s09 fidelity; Solo Teacher
  // uses the singular `firstClassSpawned.name` variant, Operator/Founder
  // share the plural `firstClassesSpawned.name`)
  'dashboard.checklist.item.centerCreated.name',
  'dashboard.checklist.item.templatePicked.name',
  'dashboard.checklist.item.firstClassesSpawned.name',
  'dashboard.checklist.item.firstClassSpawned.name',
  'dashboard.checklist.item.teachersInvited.name',
  'dashboard.checklist.item.enrolStudents.name',
  'dashboard.checklist.item.createMoreClasses.name',
  'dashboard.checklist.item.addResources.name',
  // checklist item badges (4)
  'dashboard.checklist.badge.done',
  'dashboard.checklist.badge.required',
  'dashboard.checklist.badge.optional',
  'dashboard.checklist.badge.comingSoon',
  // AI sample card (7)
  'dashboard.aiSample.title',
  'dashboard.aiSample.essayExcerpt',
  'dashboard.aiSample.feedbackQuote',
  'dashboard.aiSample.disclaimer',
  'dashboard.aiSample.bandLabel',
  'dashboard.aiSample.aiMarkLabel',
  'dashboard.aiSample.criterionAriaLabel',
  // sample owner preview (6)
  'dashboard.samplePreview.thresholdBanner',
  'dashboard.samplePreview.disclaimer',
  'dashboard.samplePreview.stat.sessionsToday',
  'dashboard.samplePreview.stat.gradingQueue',
  'dashboard.samplePreview.stat.atRiskStudents',
  'dashboard.samplePreview.stat.attendance',
  // your classes row (7)
  'dashboard.yourClasses.heading',
  'dashboard.yourClasses.ghost',
  'dashboard.yourClasses.cardAriaLabel',
  'dashboard.yourClasses.createAnotherCta',
  'dashboard.yourClasses.placeholder.students',
  'dashboard.yourClasses.placeholder.sessions',
  'dashboard.yourClasses.placeholder.nextSession',
  // dead-link toast (1)
  'dashboard.deadLink.notReady',
  // reparented from `dashboard.finishSetup.*` (AC13 4-file atomic rename)
  'dashboard.welcomeBack.banner',
  'dashboard.welcomeBack.continueCta',
  'dashboard.welcomeBack.awaitingNextStep',
] as const

describe('Story 2-4 i18n parity (R38)', () => {
  test('every Story 2-4 i18n key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_2_4_KEYS)
  })

  test('interpolation-token parity holds across en / vi for ALL 42 keys (M-BLOCKER-5 — no filtered subset)', () => {
    assertI18nInterpolationParity(STORY_2_4_KEYS)
  })

  const ALLOWED_PREFIXES_2_4 = [
    'dashboard.welcomeHeading',
    'dashboard.welcomeBack.',
    'dashboard.checklist.',
    'dashboard.aiSample.',
    'dashboard.samplePreview.',
    'dashboard.yourClasses.',
    'dashboard.deadLink.',
  ] as const

  test.each(STORY_2_4_KEYS)(
    '%s belongs to a 2-4 allowed prefix (AC13 6-prefix ratchet)',
    (key) => {
      const ok = ALLOWED_PREFIXES_2_4.some((p) => key.startsWith(p))
      expect(ok).toBe(true)
    },
  )
})

/**
 * Story 2-5a — Center Settings backend + Profile tab keys.
 * Per-story discharge of R38 (i18n parity, score 6).
 *
 * Closed-enumeration STORY_2_5A_KEYS + prefix-ratchet + `assertI18nInterpolationParity`
 * pattern mirrors STORY_2_4_KEYS above. IANA timezone labels are NOT
 * i18n'd (rendered as raw identifiers per the pragmatic scope call
 * documented in the sibling completion-notes).
 */
export const STORY_2_5A_KEYS = [
  // tab strip (4)
  'settings.tabs.profile',
  'settings.tabs.terms',
  'settings.tabs.integrations',
  'settings.tabs.rooms',
  // placeholder tab bodies (3) — REMOVED when 2-5b/2-5c land
  'settings.tabPlaceholder.terms',
  'settings.tabPlaceholder.integrations',
  'settings.tabPlaceholder.rooms',
  // Profile section chrome (5)
  'settings.profile.sectionHeading',
  'settings.profile.reopenChecklistCta',
  'settings.profile.reopenChecklist.toast',
  'settings.profile.saveCta',
  'settings.profile.saveInFlight',
  'settings.profile.saveSuccessToast',
  // Profile form fields + Zod error keys (18)
  'settings.profile.form.name.label',
  'settings.profile.form.name.placeholder',
  'settings.profile.form.name.errors.required',
  'settings.profile.form.name.errors.tooLong',
  'settings.profile.form.contactEmail.label',
  'settings.profile.form.contactEmail.placeholder',
  'settings.profile.form.contactEmail.helper',
  'settings.profile.form.contactEmail.errors.invalid',
  'settings.profile.form.shortCode.label',
  'settings.profile.form.shortCode.helperReadOnly',
  'settings.profile.form.brandColor.label',
  'settings.profile.form.brandColor.hexLabel',
  'settings.profile.form.brandColor.hexPlaceholder',
  'settings.profile.form.brandColor.errors.invalid',
  'settings.profile.form.logo.label',
  'settings.profile.form.logo.uploadCta',
  'settings.profile.form.timezone.label',
  // About card (4)
  'settings.profile.about.title',
  'settings.profile.about.created',
  'settings.profile.about.by',
  'settings.profile.about.plan',
  'settings.profile.about.id',
  // Danger Zone (3)
  'settings.profile.dangerZone.title',
  'settings.profile.dangerZone.transferOwnership',
  'settings.profile.dangerZone.archiveCenter',
  // Error catalog (10 — 5-error matrix + generic + genericWithRequestId + tryAgain + fetchWithRequestId + rateLimitWithRetry)
  'settings.error.fetch',
  'settings.error.fetchWithRequestId',
  'settings.error.tryAgain',
  'settings.error.validation',
  'settings.error.forbidden',
  'settings.error.auth',
  'settings.error.rateLimit',
  'settings.error.rateLimitWithRetry',
  'settings.error.generic',
  'settings.error.genericWithRequestId',
] as const

describe('Story 2-5a i18n parity (R38)', () => {
  test('every Story 2-5a i18n key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_2_5A_KEYS)
  })

  test('interpolation-token parity holds across en / vi for ALL Story 2-5a keys (M-BLOCKER-5)', () => {
    assertI18nInterpolationParity(STORY_2_5A_KEYS)
  })

  const ALLOWED_PREFIXES_2_5A = [
    'settings.tabs.',
    'settings.tabPlaceholder.',
    'settings.profile.',
    'settings.error.',
  ] as const

  test.each(STORY_2_5A_KEYS)(
    '%s belongs to a 2-5a allowed prefix (AC13 4-prefix ratchet)',
    (key) => {
      const ok = ALLOWED_PREFIXES_2_5A.some((p) => key.startsWith(p))
      expect(ok).toBe(true)
    },
  )
})

/**
 * Story 2-5b — Center Settings Terms + Holidays + Rooms tabs (ATDD 2026-07-15).
 * Per-story discharge of R38 (i18n parity, score 6).
 *
 * ~55 keys total across 4 surfaces: Terms + Holidays sections (shared tab
 * body), Rooms tab (incl. synthetic Google Meet row), CRUD dialog copy
 * (add/edit + delete confirm), and validation error catalog. Prefix ratchet
 * is tightened to 3 new prefixes (settings.terms., settings.holidays.,
 * settings.rooms.) since AC13 pins the story's namespace boundary. Shared
 * `settings.error.*` keys added in 2-5a are re-used without extension.
 *
 * Red signal on first run: `assertI18nParity(STORY_2_5B_KEYS)` fails on
 * every missing key with a readable diff. Amelia flips green by landing
 * en.json + vi.json entries in Task 8. `assertI18nInterpolationParity`
 * covers all 3 interpolation tokens: {{count}}, {{name}}, {{requestId}}.
 */
export const STORY_2_5B_KEYS = [
  // Cross-scoped date validator error (shared across terms + holidays).
  // Added /bmad-code-review 2-5b Round 1 P8 (2026-07-15) — replaces the
  // per-field label-as-error kludge that rendered "Start date" on any
  // date parse failure regardless of which field failed.
  'settings.common.form.date.errors.invalid',
  // Terms section (12 — was 13; overlapAdvisory removed per Round 1 D3
  // as advisory-only warning UI is deferred to FU-2-5b-F. Keeping the
  // key without a render site was misleading dead-copy.)
  'settings.terms.sectionHeading',
  'settings.terms.addCta',
  'settings.terms.empty.headline',
  'settings.terms.empty.body',
  'settings.terms.empty.cta',
  'settings.terms.row.editCta',
  'settings.terms.row.deleteCta',
  'settings.terms.state.current',
  'settings.terms.state.upcoming',
  'settings.terms.state.past',
  'settings.terms.saveSuccessToast',
  'settings.terms.deleteSuccessToast',
  // Terms form (11)
  'settings.terms.form.dialogTitleCreate',
  'settings.terms.form.dialogTitleEdit',
  'settings.terms.form.name.label',
  'settings.terms.form.name.placeholder',
  'settings.terms.form.name.errors.required',
  'settings.terms.form.name.errors.tooLong',
  'settings.terms.form.startDate.label',
  'settings.terms.form.endDate.label',
  'settings.terms.form.endDate.errors.beforeStart',
  'settings.terms.form.saveCta',
  'settings.terms.form.cancelCta',
  // Terms delete confirm (3)
  'settings.terms.delete.confirmHeadline',
  'settings.terms.delete.confirmCta',
  'settings.terms.delete.cancelCta',
  // Holidays section (7)
  'settings.holidays.sectionHeading',
  'settings.holidays.addCta',
  'settings.holidays.empty.headline',
  'settings.holidays.empty.body',
  'settings.holidays.row.editCta',
  'settings.holidays.row.deleteCta',
  'settings.holidays.saveSuccessToast',
  // Holidays form + delete (9 — +2 error keys added Round 1 P8)
  'settings.holidays.form.dialogTitleCreate',
  'settings.holidays.form.dialogTitleEdit',
  'settings.holidays.form.name.label',
  'settings.holidays.form.name.errors.required',
  'settings.holidays.form.name.errors.tooLong',
  'settings.holidays.form.date.label',
  'settings.holidays.form.saveCta',
  'settings.holidays.delete.confirmHeadline',
  'settings.holidays.delete.confirmCta',
  // Rooms section (10)
  'settings.rooms.sectionHeading',
  'settings.rooms.addCta',
  'settings.rooms.empty.headline',
  'settings.rooms.empty.body',
  'settings.rooms.empty.cta',
  'settings.rooms.row.editCta',
  'settings.rooms.row.deleteCta',
  'settings.rooms.row.capacityLabel',
  'settings.rooms.saveSuccessToast',
  'settings.rooms.deleteSuccessToast',
  // Rooms form (12)
  'settings.rooms.form.dialogTitleCreate',
  'settings.rooms.form.dialogTitleEdit',
  'settings.rooms.form.name.label',
  'settings.rooms.form.name.placeholder',
  'settings.rooms.form.name.errors.required',
  'settings.rooms.form.name.errors.tooLong',
  'settings.rooms.form.name.errors.taken',
  'settings.rooms.form.description.label',
  'settings.rooms.form.description.errors.tooLong',
  'settings.rooms.form.capacity.label',
  'settings.rooms.form.capacity.errors.range',
  'settings.rooms.form.saveCta',
  'settings.rooms.form.cancelCta',
  // Rooms delete + synthetic Meet row (5)
  'settings.rooms.delete.confirmHeadline',
  'settings.rooms.delete.confirmCta',
  'settings.rooms.delete.cancelCta',
  'settings.rooms.synthetic.meet.name',
  'settings.rooms.synthetic.meet.settingsCta',
] as const

describe('Story 2-5b i18n parity (R38)', () => {
  test('every Story 2-5b i18n key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_2_5B_KEYS)
  })

  test('interpolation-token parity holds across en / vi for ALL Story 2-5b keys (M-BLOCKER-5)', () => {
    assertI18nInterpolationParity(STORY_2_5B_KEYS)
  })

  const ALLOWED_PREFIXES_2_5B = [
    // `settings.common.` added /bmad-code-review 2-5b Round 1 P8 for the
    // cross-scoped date-validator key that both terms and holidays share.
    'settings.common.',
    'settings.terms.',
    'settings.holidays.',
    'settings.rooms.',
  ] as const

  test.each(STORY_2_5B_KEYS)(
    '%s belongs to a 2-5b allowed prefix (AC13 3-prefix ratchet)',
    (key) => {
      const ok = ALLOWED_PREFIXES_2_5B.some((p) => key.startsWith(p))
      expect(ok).toBe(true)
    },
  )
})

