/**
 * ATDD RED-PHASE SCAFFOLD — Story 1-7c AC1 (R38 mitigation, score 6).
 *
 * Generated by `/bmad-tea AT` 2026-06-11.
 *
 * This is the WF-8-mandated ATDD red specimen for R38 ("i18n key missing in
 * vi.json — Vietnamese user sees raw key"). It enumerates every i18n key
 * Story 1-7c introduces and asserts BOTH en.json AND vi.json contain it.
 *
 * STATUS: skipped (TDD red phase). The `describe.skip` block keeps the
 * existing 100/100 vitest baseline green while the scaffold sits on the
 * branch alongside the story file. To activate during dev:
 *
 *   1. Replace `describe.skip` below with `describe`.
 *   2. Run `npx vitest run i18n-parity-coverage` — it MUST go RED first
 *      against the existing 3-key locale stubs.
 *   3. Add the keys to en.json + vi.json per Story 1-7c AC1 / Task 1.x.
 *   4. Re-run — it MUST go GREEN.
 *   5. Re-run `npm run i18n-parity` (the CI script) — also GREEN.
 *
 * If you activate this test and it does NOT go red against the baseline,
 * the assertI18nParity helper has been tampered with or the keys were
 * silently pre-seeded — investigate before unsuppressing.
 *
 * Source contract: `_bmad-output/implementation-artifacts/1-7c-shared-layout-components-and-i18n.md`
 * Risk reference: `_bmad-output/test-artifacts/test-design/classlite_new-handoff.md` line 162 (R38).
 */
import { describe, expect, test } from 'vitest'
import { assertI18nParity } from '@/lib/test/i18n-parity'

/**
 * Every i18n key Story 1-7c introduces. Grouped by surface for readability.
 * Order matches AC1 in the story file. DO NOT REORDER without updating the
 * story — the grouping is the documentation.
 */
const STORY_1_7C_KEYS = [
  // AppLayout — sidebar + topbar chrome
  'app.layout.sidebar.brand',
  'app.layout.sidebar.collapseToggle',
  'app.layout.sidebar.nav.aria',
  'app.layout.topbar.breadcrumb',
  'app.layout.topbar.search',
  'app.layout.topbar.searchHint',
  'app.layout.userPill.roleLabel.owner',
  'app.layout.userPill.roleLabel.admin',
  'app.layout.userPill.roleLabel.teacher',
  'app.layout.userPill.roleLabel.student',
  'app.layout.userPill.signOut',
  'app.layout.languageToggle.aria',
  'app.layout.languageToggle.en',
  'app.layout.languageToggle.vi',
  'app.layout.skipToContent',

  // ErrorBoundary — replaces 1-7b's minimal RootErrorBoundary; the
  // `app.errorFallback` key from 1-7b is DELETED in this story.
  'app.errorBoundary.title',
  'app.errorBoundary.body',
  'app.errorBoundary.eventIdLabel',
  'app.errorBoundary.retryCta',
  'app.errorBoundary.homeLinkCta',

  // PermissionDenied — UX-DR16 orientation, two body-copy variants
  'app.permissionDenied.title',
  'app.permissionDenied.bodyOwnerAdmin',
  'app.permissionDenied.bodyOwner',
  'app.permissionDenied.contactLinkCta',
  'app.permissionDenied.homeLinkCta',
  'app.permissionDenied.requiredRoleSummaryOwnerAdmin',
  'app.permissionDenied.requiredRoleSummaryOwner',

  // NotFound — closes 1-7b's W1 catch-all defer
  'app.notFound.title',
  'app.notFound.body',
  'app.notFound.homeLinkCta',

  // Initial auth-screen keys — Stories 1-8 / 1-9a-d will consume; seeded
  // here so the parity helper has coverage and the bilingual smoke spec
  // has surface area for /login.
  'auth.login.title',
  'auth.login.submit',
  'auth.login.googleCta',
  'auth.login.emailCollapse',
  'auth.register.title',
  'auth.register.submit',
  'auth.common.email',
  'auth.common.password',
  'auth.common.passwordToggleAria',
] as const

describe('Story 1-7c i18n parity (R38)', () => {
  test('every Story 1-7c i18n key exists in both en.json and vi.json', () => {
    // Will throw with a readable diff naming each missing key per locale
    // until Task 1.2 / 1.3 add them. The assertion is intentionally
    // single-shot — one failure surfaces the entire missing-key list so
    // the dev can fix in one pass.
    assertI18nParity(STORY_1_7C_KEYS)
  })

  test('legacy 1-7b key app.errorFallback is REMOVED from both locales', () => {
    // Story 1-7c deletes `app.errorFallback` because the polished
    // ErrorBoundary uses `app.errorBoundary.*` instead. If this assertion
    // fails GREEN (key exists), Task 1.6 was skipped — the polished
    // boundary works AND the old key sits unreferenced.
    expect(() => assertI18nParity(['app.errorFallback'])).toThrow(
      /i18n parity check failed/,
    )
  })
})

