/**
 * ATDD RED-PHASE SCAFFOLD — Story 1-7c AC1 (R38 mitigation, score 6).
 *
 * Generated by `/bmad-tea AT` 2026-06-11.
 *
 * This is the WF-8-mandated ATDD red specimen for R38 ("i18n key missing in
 * vi.json — Vietnamese user sees raw key"). It enumerates every i18n key
 * Story 1-7c introduces and asserts BOTH en.json AND vi.json contain it.
 *
 * STATUS: skipped (TDD red phase). The `describe.skip` block keeps the
 * existing 100/100 vitest baseline green while the scaffold sits on the
 * branch alongside the story file. To activate during dev:
 *
 *   1. Replace `describe.skip` below with `describe`.
 *   2. Run `npx vitest run i18n-parity-coverage` — it MUST go RED first
 *      against the existing 3-key locale stubs.
 *   3. Add the keys to en.json + vi.json per Story 1-7c AC1 / Task 1.x.
 *   4. Re-run — it MUST go GREEN.
 *   5. Re-run `npm run i18n-parity` (the CI script) — also GREEN.
 *
 * If you activate this test and it does NOT go red against the baseline,
 * the assertI18nParity helper has been tampered with or the keys were
 * silently pre-seeded — investigate before unsuppressing.
 *
 * Source contract: `_bmad-output/implementation-artifacts/1-7c-shared-layout-components-and-i18n.md`
 * Risk reference: `_bmad-output/test-artifacts/test-design/classlite_new-handoff.md` line 162 (R38).
 */
import { describe, expect, test } from 'vitest'
import { assertI18nParity } from '@/lib/test/i18n-parity'

/**
 * Every i18n key Story 1-7c introduces. Grouped by surface for readability.
 * Order matches AC1 in the story file. DO NOT REORDER without updating the
 * story — the grouping is the documentation.
 */
const STORY_1_7C_KEYS = [
  // AppLayout — sidebar + topbar chrome.
  // Story 1d-3 migrated:
  //   app.layout.sidebar.brand          → sidebar.brand
  //   app.layout.sidebar.collapseToggle → sidebar.collapseToggle
  //   app.layout.sidebar.nav.aria       → sidebar.nav.primary
  //   app.layout.topbar.breadcrumb      → topbar.breadcrumb.label
  //   app.layout.topbar.search          → topbar.search.placeholder
  //   app.layout.topbar.searchHint      → topbar.search.hint
  //   app.layout.userPill.roleLabel.*   → userPill.role.*
  // Migrated keys now appear in STORY_1D_3_KEYS below. The keys retained
  // here are still consumed by 1-7c's own surfaces (`AppLayout`, language
  // toggle, sign-out CTA).
  'app.layout.userPill.signOut',
  'app.layout.languageToggle.aria',
  'app.layout.languageToggle.en',
  'app.layout.languageToggle.vi',
  'app.layout.skipToContent',

  // ErrorBoundary — replaces 1-7b's minimal RootErrorBoundary; the
  // `app.errorFallback` key from 1-7b is DELETED in this story.
  'app.errorBoundary.title',
  'app.errorBoundary.body',
  'app.errorBoundary.eventIdLabel',
  'app.errorBoundary.retryCta',
  'app.errorBoundary.homeLinkCta',

  // PermissionDenied — UX-DR16 orientation, two body-copy variants
  'app.permissionDenied.title',
  'app.permissionDenied.bodyOwnerAdmin',
  'app.permissionDenied.bodyOwner',
  'app.permissionDenied.contactLinkCta',
  'app.permissionDenied.homeLinkCta',
  'app.permissionDenied.requiredRoleSummaryOwnerAdmin',
  'app.permissionDenied.requiredRoleSummaryOwner',

  // NotFound — closes 1-7b's W1 catch-all defer
  'app.notFound.title',
  'app.notFound.body',
  'app.notFound.homeLinkCta',

  // Initial auth-screen keys — Stories 1-8 / 1-9a-d will consume; seeded
  // here so the parity helper has coverage and the bilingual smoke spec
  // has surface area for /login.
  'auth.login.title',
  'auth.login.submit',
  'auth.login.googleCta',
  'auth.login.emailCollapse',
  'auth.register.title',
  'auth.register.submit',
  'auth.common.email',
  'auth.common.password',
  'auth.common.passwordToggleAria',
] as const

/**
 * Story 1d-2 — Storybook placeholder keys introduced by AC8. The
 * primitive `*.tsx` files do NOT consume i18n strings (presentational
 * shells); the assertion target is the demo copy rendered inside the
 * `*.stories.tsx` files (toast bodies, command empty-results text,
 * label suffixes, form placeholders, long Vietnamese tooltip / popover
 * fixtures). Per-story discharge of R38 — NOT a separate ATDD ceremony.
 */
const STORY_1D_2_KEYS = [
  'storybook.toast.success',
  'storybook.toast.error',
  'storybook.toast.info',
  'storybook.command.empty',
  'storybook.label.required',
  'storybook.label.optional',
  'storybook.placeholder.email',
  'storybook.placeholder.name',
  'storybook.placeholder.longViText',
  // Code review 2026-06-17 — Form story play asserts locale-correct
  // validation copy. Schema messages and demo labels live as keys so the
  // FormMessage component renders the localized copy in both en + vi.
  'storybook.form.emailInvalid',
  'storybook.form.nameRequired',
  'storybook.form.agreedRequired',
  'storybook.form.emailHelp',
  'storybook.form.nameLabel',
  'storybook.form.agreedLabel',
  // Calendar / Popover / Tooltip — replace hardcoded Vietnamese copy
  // (`buổi học hôm nay`, `Trạng thái`) with keys so the `en` locale renders
  // English content instead of Vietnamese.
  'storybook.calendar.eventToday',
  'storybook.popover.statusTitle',
  'storybook.tooltip.statusTrigger',
  // Input / Textarea — replace `auth.common.email` reuse on non-email
  // labels and the `storybook.placeholder.longViText` reuse as a fake
  // error message.
  'storybook.textarea.label',
  'storybook.textarea.helper',
  'storybook.textarea.errorTooLong',
  'storybook.textarea.readOnlyContents',
  'storybook.input.hoursLabel',
  'storybook.input.hoursHelper',
] as const

describe('Story 1d-2 i18n parity (R38)', () => {
  test('every Story 1d-2 storybook key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1D_2_KEYS)
  })
})

/**
 * Story 1d-3 — app-shell stack keys. Per-story discharge of R38 for the
 * domain components: AppShell, SidebarShell (× 4 role variants),
 * SidebarNavItem, UserPill, TopbarShell, BreadcrumbBar, SearchPill,
 * PageHead, MobileTabBar (× 3 role variants), MobileTab.
 *
 * Grouped by namespace for readability. Namespace coverage is enforced by
 * `scripts/i18n-parity.mjs` — every `sidebar.*` / `topbar.*` /
 * `mobileTab.*` / `pageHead.*` / `userPill.*` / `appShell.*` key MUST
 * appear in some `STORY_1D_*_KEYS` array exported below. An orphan key
 * (in JSON but not enumerated anywhere) fails the script.
 */
export const STORY_1D_3_KEYS = [
  // AppShell
  'appShell.root',

  // Sidebar chrome + aria templates
  'sidebar.brand',
  'sidebar.nav.primary',
  'sidebar.nav.unreadAria',
  'sidebar.collapseToggle',
  'sidebar.section.workspace',
  'sidebar.section.resources',
  'sidebar.section.settings',

  // Sidebar — Owner nav
  'sidebar.owner.dashboard',
  'sidebar.owner.people',
  'sidebar.owner.classes',
  'sidebar.owner.schedule',
  'sidebar.owner.analytics',
  'sidebar.owner.inbox',
  'sidebar.owner.knowledgeHub',
  'sidebar.owner.archive',
  'sidebar.owner.settings',

  // Sidebar — Admin nav (Owner MINUS Settings)
  'sidebar.admin.dashboard',
  'sidebar.admin.people',
  'sidebar.admin.classes',
  'sidebar.admin.schedule',
  'sidebar.admin.analytics',
  'sidebar.admin.inbox',
  'sidebar.admin.knowledgeHub',
  'sidebar.admin.archive',

  // Sidebar — Teacher nav
  'sidebar.teacher.dashboard',
  'sidebar.teacher.classes',
  'sidebar.teacher.schedule',
  'sidebar.teacher.exercises',
  'sidebar.teacher.questions',
  'sidebar.teacher.students',
  'sidebar.teacher.analytics',
  'sidebar.teacher.inbox',
  'sidebar.teacher.knowledgeHub',
  'sidebar.teacher.archive',

  // Sidebar — Student nav (student-tone labels)
  'sidebar.student.dashboard',
  'sidebar.student.myClasses',
  'sidebar.student.assignments',
  'sidebar.student.mySchedule',
  'sidebar.student.questions',
  'sidebar.student.myPerformance',
  'sidebar.student.inbox',

  // Topbar
  'topbar.breadcrumb.label',
  'topbar.breadcrumb.more',
  'topbar.search.placeholder',
  'topbar.search.hint',

  // UserPill role labels
  'userPill.role.owner',
  'userPill.role.admin',
  'userPill.role.teacher',
  'userPill.role.student',

  // MobileTabBar chrome (nav landmark label distinct from desktop sidebar's)
  'mobileTab.nav.primary',

  // MobileTabBar — Student tabs (per IA `s74–s81`)
  'mobileTab.student.home',
  'mobileTab.student.assignments',
  'mobileTab.student.inbox',
  'mobileTab.student.classes',
  'mobileTab.student.me',

  // MobileTabBar — Teacher tabs (per IA `s82–s85`)
  'mobileTab.teacher.home',
  'mobileTab.teacher.classes',
  'mobileTab.teacher.inbox',
  'mobileTab.teacher.schedule',
  'mobileTab.teacher.me',

  // MobileTabBar — Owner tabs (extrapolated; per `s86`)
  'mobileTab.owner.home',
  'mobileTab.owner.people',
  'mobileTab.owner.inbox',
  'mobileTab.owner.analytics',
  'mobileTab.owner.me',

  // PageHead fixture (storybook demo only)
  'pageHead.fixture.title',
  'pageHead.fixture.subtitle',
] as const

describe('Story 1d-3 i18n parity (R38)', () => {
  test('every Story 1d-3 key exists in both en.json and vi.json', () => {
    assertI18nParity(STORY_1D_3_KEYS)
  })
})

describe('Story 1-7c i18n parity (R38)', () => {
  test('every Story 1-7c i18n key exists in both en.json and vi.json', () => {
    // Will throw with a readable diff naming each missing key per locale
    // until Task 1.2 / 1.3 add them. The assertion is intentionally
    // single-shot — one failure surfaces the entire missing-key list so
    // the dev can fix in one pass.
    assertI18nParity(STORY_1_7C_KEYS)
  })

  test('legacy 1-7b key app.errorFallback is REMOVED from both locales', () => {
    // Story 1-7c deletes `app.errorFallback` because the polished
    // ErrorBoundary uses `app.errorBoundary.*` instead. If this assertion
    // fails GREEN (key exists), Task 1.6 was skipped — the polished
    // boundary works AND the old key sits unreferenced.
    expect(() => assertI18nParity(['app.errorFallback'])).toThrow(
      /i18n parity check failed/,
    )
  })
})

