/**
 * ATDD RED-PHASE SCAFFOLD — Story 1-7c AC8 (R38 mitigation, score 6).
 *
 * Generated by `/bmad-tea AT` 2026-06-11.
 *
 * Bilingual smoke + full-page axe audit. Walks the public routes Story
 * 1-7c lights up (`/login` via AuthLayout, `/permission-denied`,
 * `/this/does/not/exist` → NotFound catch-all, `/dashboard`) in BOTH
 * `lang=en` and `lang=vi` contexts and asserts:
 *
 *   1. No raw dotted i18n keys leak into the rendered DOM body text.
 *   2. Specific landmark text matches the locale JSON value (single source
 *      of truth — imported from src/locales/*.json so the spec stays in
 *      sync if the value changes).
 *   3. The skip-to-content link is the first focusable element (WCAG
 *      2.4.1 + project-context TEST-UX-2).
 *   4. `@axe-core/playwright` audit on each visited URL returns zero
 *      violations (WCAG 2.1 AA).
 *
 * STATUS: skipped (TDD red phase). The `test.describe.skip` block keeps
 * the existing 13/13 design-system Playwright baseline green while the
 * scaffold sits on the branch. To activate during dev:
 *
 *   1. Replace `test.describe.skip` with `test.describe`.
 *   2. Run `npx playwright test --project=design-system bilingual-smoke`
 *      — it MUST go RED first because Story 1-7c's components / routes /
 *      cookie wiring do not exist yet.
 *   3. Implement Tasks 1–6 of Story 1-7c (i18n keys, AppLayout, polished
 *      ErrorBoundary, PermissionDenied, NotFound + catch-all route,
 *      language cookie bridge + LanguageToggle).
 *   4. Re-run — it MUST go GREEN across both locales.
 *
 * Source contract: `_bmad-output/implementation-artifacts/1-7c-shared-layout-components-and-i18n.md`
 * Risk reference: `_bmad-output/test-artifacts/test-design/classlite_new-handoff.md` line 162 (R38).
 *
 * Why we import the locale JSON at test build time: hardcoded English
 * assertions like `toContainText('Sign in')` couple the test to one
 * locale and hide drift between the test's expectation and the actual
 * displayed value (project-context TEST-FE-4). Importing the canonical
 * value means the test stays correct if Story 1-7c's reviewer revises
 * the Vietnamese copy in-PR.
 */
import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import enLocale from '../src/locales/en.json' with { type: 'json' }
import viLocale from '../src/locales/vi.json' with { type: 'json' }

// Matches `app.layout.userPill.signOut`, `auth.login.title`, etc. Requires
// at least one dot AND only lowercase + digits + underscore on each side
// of the dots, so class names like `bg-[var(--cl-ink)]` and Tailwind
// arbitrary values are NOT matched (they contain brackets / dashes).
// Anchored to word boundaries so abbreviations like "v1.7" in copy don't
// false-positive.
const RAW_KEY_REGEX = /\b[a-z][a-zA-Z0-9_-]*(?:\.[a-z][a-zA-Z0-9_-]*){2,}\b/

async function assertNoRawKeysInDom(page: Page): Promise<void> {
  const visibleText = await page.locator('body').innerText()
  const match = visibleText.match(RAW_KEY_REGEX)
  if (match) {
    throw new Error(
      `Raw i18n key leaked into DOM: "${match[0]}". ` +
        `Add the missing key to en.json/vi.json, or fix the t() call ` +
        `that produced it. Full match context: ${visibleText
          .substring(Math.max(0, match.index! - 40), match.index! + 80)
          .replace(/\s+/g, ' ')}`,
    )
  }
}

type Locale = 'en' | 'vi'

interface LocaleProbe {
  lang: Locale
  loginTitle: string
  permissionDeniedTitle: string
  notFoundTitle: string
  errorBoundaryRetry: string
}

const PROBES: readonly LocaleProbe[] = [
  {
    lang: 'en',
    // Cast is safe — the parity-coverage test in
    // src/lib/test/__tests__/i18n-parity-coverage.test.ts asserts every key
    // in this probe exists in en.json before this spec runs in CI.
    loginTitle: (enLocale as Record<string, string>)['auth.login.title'],
    permissionDeniedTitle: (enLocale as Record<string, string>)[
      'app.permissionDenied.title'
    ],
    notFoundTitle: (enLocale as Record<string, string>)['app.notFound.title'],
    errorBoundaryRetry: (enLocale as Record<string, string>)[
      'app.errorBoundary.retryCta'
    ],
  },
  {
    lang: 'vi',
    loginTitle: (viLocale as Record<string, string>)['auth.login.title'],
    permissionDeniedTitle: (viLocale as Record<string, string>)[
      'app.permissionDenied.title'
    ],
    notFoundTitle: (viLocale as Record<string, string>)['app.notFound.title'],
    errorBoundaryRetry: (viLocale as Record<string, string>)[
      'app.errorBoundary.retryCta'
    ],
  },
]

for (const probe of PROBES) {
  test.describe(`bilingual smoke — lang=${probe.lang}`, () => {
    test.beforeEach(async ({ context }) => {
      // The design-system project runs against http://localhost:5173 (plain
      // host — no .classlite.localhost). Set the cookie on the bare host
      // so the dashboard's `readLanguageCookie()` from Story 1-7c AC6 reads
      // it on app boot.
      await context.clearCookies()
      await context.addCookies([
        { name: 'lang', value: probe.lang, domain: 'localhost', path: '/' },
      ])
    })

    test('/login renders localized title + zero axe violations + no raw keys', async ({
      page,
    }) => {
      await page.goto('/login')
      // The auth/login surface itself ships with Story 1-8. For 1-7c the
      // visible expectation is the route is reachable AND the i18n keys
      // resolve. The H1 assertion will pass once Story 1-8 lands the real
      // LoginPage; until then the placeholder route from 1-7b is rendered
      // and this assertion fails — that's the RED signal for downstream
      // sequencing. If Story 1-8 is sequenced ahead of activating this
      // scaffold, swap the locator to whatever the LoginPage H1 actually
      // resolves to.
      await expect(page.locator('h1')).toContainText(probe.loginTitle)
      await assertNoRawKeysInDom(page)
      const result = await new AxeBuilder({ page }).analyze()
      expect(result.violations).toEqual([])
    })

    test('/permission-denied renders localized title + zero axe violations', async ({
      page,
    }) => {
      await page.goto('/permission-denied')
      await expect(page.locator('h1')).toContainText(probe.permissionDeniedTitle)
      await assertNoRawKeysInDom(page)
      const result = await new AxeBuilder({ page }).analyze()
      expect(result.violations).toEqual([])
    })

    test('catch-all route renders NotFound with localized title + no raw keys', async ({
      page,
    }) => {
      await page.goto('/this/path/intentionally/does/not/exist')
      await expect(page.locator('h1')).toContainText(probe.notFoundTitle)
      await assertNoRawKeysInDom(page)
    })

    test('/dashboard skip-to-content link is the first focusable element', async ({
      page,
    }) => {
      // WCAG 2.4.1 + project-context TEST-UX-2. The skip link is the
      // FIRST element to receive focus on Tab; pressing Enter focuses
      // the <main> region. Without this, keyboard users have to tab
      // through the entire sidebar nav before reaching page content.
      await page.goto('/dashboard')
      // /dashboard is wrapped in AppLayout via a pathless lazy route.
      // Wait for the layout chunk to render before pressing Tab —
      // otherwise the keypress lands on `<body>` before the skip link
      // exists in the DOM.
      const skipLink = page.locator('a[href="#main-content"]')
      await skipLink.waitFor({ state: 'attached' })
      await page.keyboard.press('Tab')
      const focused = await page.evaluate(() => {
        const el = document.activeElement as HTMLElement | null
        if (!el) return null
        return {
          tag: el.tagName,
          href: el.getAttribute('href'),
        }
      })
      expect(focused?.tag).toBe('A')
      expect(focused?.href).toBe('#main-content')
    })

    test('/dashboard full-page axe audit returns zero violations', async ({
      page,
    }) => {
      await page.goto('/dashboard')
      // ─── LOAD-BEARING WAIT — DO NOT REMOVE OR INCREASE THE TIMEOUT ───
      //
      // Waits for AppLayout hydration. The skip-to-content link is the
      // FIRST element AppLayout renders, so its presence means both the
      // dashboard chunk AND the layout chunk have hydrated. Without this
      // wait, axe occasionally analyzes the empty-shell HTML and reports
      // `landmark-one-main` / `page-has-heading-one` violations that
      // disappear on the very next paint.
      //
      // Story 1d-3 (2026-06-19) made AppLayout heavier — 10 new domain
      // imports — and the hydration race surfaced. Story 1d-3 party-mode
      // review (Murat, 2026-06-21) flagged this comment-less wait as
      // tech-debt: a future maintainer would see an opaque `waitFor` and
      // either delete it or raise the timeout when it flakes again.
      //
      // Future-you: if this wait times out, the right move is NOT to
      // raise the timeout. The right move is to investigate AppLayout
      // hydration perf. A reasonable budget is <500ms from
      // `domcontentloaded`; if you find it taking longer, the dashboard
      // chunk graph has regressed and a fix in the lazy-import topology
      // is the actual repair. Track this in a follow-up perf-budget
      // assertion (see Story 1d-3 follow-up tasks #16-#21 backlog).
      // ────────────────────────────────────────────────────────────────
      await page.locator('a[href="#main-content"]').waitFor({ state: 'attached' })
      await assertNoRawKeysInDom(page)
      const result = await new AxeBuilder({ page }).analyze()
      // If a violation is found, the result includes node selectors + a
      // remediation summary; surface the full violation list in the
      // assertion message for fast debugging.
      expect(
        result.violations,
        `axe violations on /dashboard with lang=${probe.lang}:\n` +
          JSON.stringify(result.violations, null, 2),
      ).toEqual([])
    })
  })
}
