/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the API
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email/password registration (story 1.4)
         * @description Creates a new user account and sends a verification email. The
         *     `emailDelivery` field in the response is always present:
         *     `"sent"` when the verification email was enqueued cleanly,
         *     `"failed"` when the retry queue rejected the job (buffer full — no
         *     async retry will occur; the client should prompt the user to hit
         *     Resend Verification). `"delayed"` is reserved for future use cases.
         *     Returns 409 EMAIL_ALREADY_REGISTERED for any duplicate regardless of
         *     verification status (anti-enumeration).
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify email via token (story 1.4)
         * @description Consumes the verification token, sets `users.email_verified = true`,
         *     and invalidates any other unconsumed tokens for the same user. The
         *     operation is idempotent — replaying any prior-issued token after the
         *     user is verified also returns 200.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend verification email (story 1.4)
         * @description Rotates the user's verification token (invalidating any prior
         *     unconsumed tokens) and sends a new email. Returns 200 with
         *     `verifyPollId: null` when the email is unknown OR already verified,
         *     to prevent enumeration. All 200 responses are padded to ≥ 200 ms.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email/password login (story 1.5)
         * @description Verifies credentials and issues a 15-minute access token + a refresh
         *     token (7d default, 30d with rememberMe). The refresh token is set as
         *     an httpOnly cookie (all four cookie attributes per AC10); the
         *     response body NEVER includes the refresh token. After 5 failed
         *     attempts within 10 minutes, the account is locked for 15 minutes —
         *     subsequent attempts (even with the correct password) return 429
         *     ACCOUNT_LOCKED with a Retry-After header.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate session tokens (story 1.5)
         * @description Atomically DELETEs the presented refresh token row and INSERTs a
         *     fresh one in the same family. Reuse of a rotated-out token triggers
         *     family revocation (every refresh in the family is deleted), and the
         *     response is 401 REFRESH_TOKEN_REUSE_DETECTED.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate refresh token and clear cookie (story 1.5)
         * @description Hard-deletes the matching refresh_tokens row and emits a clearing
         *     Set-Cookie. Idempotent — unknown / missing / already-revoked
         *     cookies still return 200.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password-reset email (story 1.5)
         * @description Sends a reset email (1 hour TTL) when the email is known and
         *     verified. Returns the same 200 envelope for unknown / unverified
         *     emails — anti-enumeration. All 200 responses are padded to ≥ 200ms.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply password reset (story 1.5)
         * @description Consumes the reset token, updates the password, DELETEs every
         *     refresh_tokens row for the user (force re-login everywhere), and
         *     clears login_attempts. Replaying a consumed token returns 409
         *     RESET_TOKEN_CONSUMED; an expired token returns 410
         *     RESET_TOKEN_EXPIRED.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate Google OAuth sign-in (story 1.6)
         * @description Generates a CSRF-bound signed state token, sets the `oauth_state`
         *     httpOnly cookie (Path=/api/auth, Max-Age=600), and 302-redirects to
         *     Google's authorization URL. Optional `inviteToken` is verified
         *     pre-flight to short-circuit a wasted Google round-trip; `redirectTo`
         *     is honored only when it matches the same-origin allowlist.
         */
        get: operations["googleInit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth callback (story 1.6)
         * @description Always returns 302. Success → `APP_POST_LOGIN_URL` plus
         *     `?invited=true&center=<name>` when an invite was accepted, or
         *     `?error=<code>` for invite-recoverable failures. Failure →
         *     `APP_LOGIN_ERROR_URL_BASE?error=<code>`. Codes: `csrf_invalid`,
         *     `csrf_expired`, `google_exchange_failed`, `google_userinfo_failed`,
         *     `google_timeout`, `google_email_unverified`, `google_access_denied`,
         *     `google_server_error`, `oauth_wrong_tenant`, `google_link_race`,
         *     `invite_email_mismatch`, `invite_expired`, `invite_already_accepted`.
         *     The `oauth_state` cookie is cleared on every exit path.
         *     OAUTH_NOT_CONFIGURED is the only response that is NOT a 302 — it
         *     emits a 503 JSON envelope so operator monitoring picks it up.
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a staff invite via email/password (story 1.6)
         * @description Two branches based on whether the invite email matches an existing
         *     user. New users supply `fullName` + `password`; existing users
         *     omit both. The invite link is the email verification — accepted
         *     users land with `emailVerified: true`. Per-IP rate limited
         *     (10 / 60s) to defend against token enumeration.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/force-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Owner-initiated force-logout for a staff member (story 1.6 / FR-80)
         * @description Bulk-deletes every `refresh_tokens` row for the target user.
         *     Documented limitation: access tokens already issued remain valid
         *     for up to AccessTokenTTL (15 min) — EDGE-2 tradeoff accepted.
         *     Cross-tenant targets return 404 USER_NOT_FOUND (NEVER 403, which
         *     would leak existence). Requires authenticated Owner JWT.
         */
        post: operations["forceLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll current verification state (story 1.4)
         * @description Returns the user's current `emailVerified` state given a poll ID. The
         *     poll ID is the `email_verifications.id` of the row issued at
         *     registration or resend. Poll IDs expire 24 hours after creation,
         *     matching the verification token TTL. Unknown, malformed, or expired
         *     poll IDs all return the same 404 POLL_ID_NOT_FOUND.
         */
        get: operations["verifyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/persona": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set the authenticated user's persona (story 2.1)
         * @description Writes the caller's persona choice to `users.persona`. Idempotent — a
         *     repeat POST with the same value returns 200, not 409, so the wizard
         *     may hit this on browser back. Unknown persona values → 422.
         */
        post: operations["setOnboardingPersona"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/centers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a center + bind creator as Owner (story 2.1)
         * @description Single transaction — inserts the center row, generates a unique
         *     `shortCode` (slug + retry), inserts `center_members` with role=owner,
         *     writes an `audit_logs` row `center.created`, and returns a fresh
         *     access token whose claims include the new center+role. v1 supports
         *     one center per user — a repeat attempt returns 409
         *     USER_ALREADY_HAS_CENTER.
         */
        post: operations["createCenter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/centers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch center profile — Owner-only, tenant-bound (story 2-5a)
         * @description Returns the caller's center profile (Owner-only per AC2). The
         *     path `{id}` MUST equal the caller's tenant-context centerID; a
         *     mismatch returns 403 `TENANT_MISMATCH`. `centers` is a global
         *     table (no RLS), so the tenant check happens at the handler layer.
         */
        get: operations["getCenterProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partial-update center profile — Owner-only (story 2-5a)
         * @description Partial update of name / contactEmail / brandColor / logoUrl / timezone.
         *     Only present fields update; omitted fields are left unchanged (COALESCE
         *     pattern in the SQL layer). `shortCode` is intentionally absent from
         *     the request schema — the Settings UI renders it as a read-only input
         *     (AC3) and any client that sends it is silently ignored by the API.
         *     Timezone must be one of the 30-entry IANA whitelist (see enum below);
         *     anything else returns 422 `UNSUPPORTED_TIMEZONE`.
         */
        patch: operations["updateCenterProfile"];
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accessible templates — system seeds + caller's center-owned (story 2.2)
         * @description Returns the concatenation of the caller's accessible class templates:
         *     (a) global system seeds (`class_templates.center_id IS NULL`, at least
         *     5 rows — see AC1b), then (b) center-owned custom templates ordered by
         *     `created_at DESC`. Response includes a per-row `scope` discriminator
         *     (`"system" | "center"`) so the wizard can render them distinctly.
         */
        get: operations["listTemplates"];
        put?: never;
        /**
         * Create a center-owned custom template with pre-configured sessions (story 2.2)
         * @description Inserts a `class_templates` row scoped to the caller's center and all
         *     provided `template_sessions` rows in a SINGLE transaction. Validation
         *     enforces `sessions.length == sessionCount` as the single source of
         *     truth — any drift returns 422.
         */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}/spawn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spawn N classes atomically from a template (story 2.2)
         * @description Reads the template (system OR own — RLS renders other tenants' rows
         *     invisible → 404 TEMPLATE_NOT_FOUND) then, in ONE transaction, inserts
         *     N `classes` rows, resolves each class's teacher via Branch A/B/C/D,
         *     writes optional `invites` rows for pending teachers, and writes one
         *     `audit_logs` row `class.spawned` per class. On ANY failure the whole
         *     tx rolls back — zero classes, zero invites, zero audit rows. Invite
         *     emails are enqueued AFTER commit through `EmailRetryQueue`
         *     (best-effort — the invite ROW is the durable contract).
         */
        post: operations["spawnClasses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's onboarding progress (story 2.1)
         * @description Returns the caller's saved onboarding progress row plus their
         *     current persona. Never 404s — when no progress row exists, responds
         *     200 with `{currentStep: "persona", payload: null, updatedAt: null}`
         *     and the caller's persona (which may itself be null).
         */
        get: operations["getOnboardingProgress"];
        /**
         * Upsert the caller's onboarding progress (story 2.1)
         * @description Upserts a single row per user in `onboarding_progress` keyed by
         *     `user_id`. Unknown `currentStep` → 422.
         */
        put: operations["putOnboardingProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        VerifyEmailRequest: {
            token: string;
        };
        ResendVerificationRequest: {
            /** Format: email */
            email: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @default false */
            rememberMe: boolean;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
        SetPersonaRequest: {
            /** @enum {string} */
            persona: "operator" | "founder" | "solo_teacher";
        };
        CreateCenterRequest: {
            name: string;
            /** @description Hex color like `#3B82F6`. Nullable in v1. */
            brandColor?: string | null;
            /** @description Presigned R2 asset URL (finalized in a later story). Nullable in v1. */
            logoUrl?: string | null;
        };
        /**
         * @description Story 2-5a partial-update — all fields optional. Only present fields
         *     are applied (COALESCE pattern in SQL). `shortCode` is intentionally
         *     absent per AC3 (rendered read-only in the Settings UI; changing it
         *     would break existing class codes).
         */
        UpdateCenterProfileRequest: {
            name?: string;
            /**
             * Format: email
             * @description Optional. Persisted to `centers.contact_email`. Used later
             *     (FU-2-5-G) as reply-to for staff/student notification emails —
             *     consumption is out of scope for story 2-5a.
             */
            contactEmail?: string | null;
            brandColor?: string | null;
            logoUrl?: string | null;
            /**
             * @description IANA timezone. MUST be one of the 30-entry whitelist below.
             *     Anything else returns 422 UNSUPPORTED_TIMEZONE.
             * @enum {string}
             */
            timezone?: "Asia/Ho_Chi_Minh" | "Asia/Bangkok" | "Asia/Singapore" | "Asia/Jakarta" | "Asia/Manila" | "Asia/Kuala_Lumpur" | "Asia/Hong_Kong" | "Asia/Shanghai" | "Asia/Taipei" | "Asia/Seoul" | "Asia/Tokyo" | "Asia/Dubai" | "Asia/Kolkata" | "Asia/Karachi" | "Europe/London" | "Europe/Paris" | "Europe/Berlin" | "Europe/Amsterdam" | "Europe/Madrid" | "Europe/Warsaw" | "Europe/Moscow" | "Europe/Istanbul" | "America/New_York" | "America/Chicago" | "America/Denver" | "America/Los_Angeles" | "America/Toronto" | "America/Sao_Paulo" | "Australia/Sydney" | "Pacific/Auckland";
        };
        /**
         * @description Typed JSONB payload written to `onboarding_progress.payload`. Story 2.1
         *     pins `schemaVersion: 1`. `templateDraft` remains opaque JSON until
         *     story 2.2 pins its shape.
         */
        OnboardingProgressPayload: {
            /** @constant */
            schemaVersion: 1;
            /** @enum {string|null} */
            personaChoice?: "operator" | "founder" | "solo_teacher" | null;
            centerDraft?: {
                name: string;
                brandColor?: string | null;
                logoUrl?: string | null;
            } | null;
            templateDraft?: {
                [key: string]: unknown;
            } | null;
        };
        PutOnboardingProgressRequest: {
            /** @enum {string} */
            currentStep: "persona" | "center" | "template" | "spawn" | "solo_first_class" | "done";
            payload: components["schemas"]["OnboardingProgressPayload"];
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
            emailVerified: boolean;
        };
        RegisterResult: {
            user: components["schemas"]["UserSummary"];
            /** Format: uuid */
            verifyPollId: string;
            /**
             * @description `sent` — verification email was enqueued for delivery. `delayed` —
             *     reserved for future use when a send is genuinely postponed rather
             *     than dropped. `failed` — the retry queue rejected the job (buffer
             *     full); no async retry will occur. The frontend should prompt the
             *     user to hit Resend Verification when it sees `failed`.
             * @enum {string}
             */
            emailDelivery: "sent" | "delayed" | "failed";
        };
        VerifyEmailResult: {
            verified: boolean;
            /** Format: email */
            email: string;
        };
        ResendResult: {
            /** Format: uuid */
            verifyPollId: string | null;
        };
        VerifyStatusResult: {
            verified: boolean;
            /** Format: email */
            email: string;
        };
        LoginResult: {
            /** @description HS256-signed JWT, 15-minute expiry. */
            accessToken: string;
            user: components["schemas"]["UserSummary"];
        };
        LogoutResult: {
            loggedOut: boolean;
        };
        ForgotPasswordResult: {
            /** @description Always true on a 200 — does not indicate whether an email was actually dispatched (anti-enumeration). */
            sent: boolean;
        };
        ResetPasswordResult: {
            reset: boolean;
        };
        SetPersonaResult: {
            /** @enum {string} */
            persona: "operator" | "founder" | "solo_teacher";
        };
        /**
         * @description Story 2-5a Settings Profile tab payload. Includes contactEmail (new
         *     in this story) and googleMeetConnected (existing on the row; used
         *     by the Integrations tab in 2-5c).
         */
        CenterProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            shortCode: string;
            /** Format: email */
            contactEmail: string | null;
            brandColor: string | null;
            logoUrl: string | null;
            /** @description IANA timezone (see UpdateCenterProfileRequest enum for the accepted set). */
            timezone: string;
            googleMeetConnected: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateCenterResult: {
            /** Format: uuid */
            id: string;
            name: string;
            shortCode: string;
            brandColor: string | null;
            logoUrl: string | null;
            /**
             * @description Center's timezone in IANA format. Defaults to `Asia/Ho_Chi_Minh`
             *     in v1 — story 2.5 exposes edit capability.
             */
            timezone: string;
            /**
             * @description v1 always `owner` regardless of persona (see FU-2-1-F).
             * @enum {string}
             */
            role: "owner";
            /** @description Fresh HS256 JWT with centerId+role claims, 15-minute TTL. */
            accessToken: string;
            /**
             * Format: date-time
             * @description ISO-8601 UTC expiry for the new access token.
             */
            expiresAt: string;
        };
        OnboardingProgressResult: {
            /** @enum {string} */
            currentStep: "persona" | "center" | "template" | "spawn" | "solo_first_class" | "done";
            payload: components["schemas"]["OnboardingProgressPayload"] | null;
            /** Format: date-time */
            updatedAt: string | null;
            /** @enum {string|null} */
            persona: "operator" | "founder" | "solo_teacher" | null;
        };
        PutOnboardingProgressResult: {
            /** @enum {string} */
            currentStep: "persona" | "center" | "template" | "spawn" | "solo_first_class" | "done";
            payload: components["schemas"]["OnboardingProgressPayload"];
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTemplateRequest: {
            /** @description Rune-count limits (`utf8.RuneCountInString`) — a Vietnamese template name of 120 characters is fine even though the UTF-8 byte length exceeds 120. */
            name: string;
            /** @description IELTS band target — allowed values 1.0..9.0 in 0.5 steps. */
            targetBand: number;
            /** @enum {string} */
            primarySkill: "writing" | "speaking" | "listening" | "reading" | "listening_reading" | "all_skills";
            sessionCount: number;
            color: string | null;
            /** @description MUST equal length of sessionCount (AC2 single-source-of-truth). */
            sessions: components["schemas"]["TemplateSessionInput"][];
        };
        TemplateSessionInput: {
            title: string;
            description: string | null;
        };
        Template: {
            /** Format: uuid */
            id: string;
            name: string;
            targetBand: number;
            /** @enum {string} */
            primarySkill: "writing" | "speaking" | "listening" | "reading" | "listening_reading" | "all_skills";
            sessionCount: number;
            color: string | null;
            /** @enum {string} */
            scope: "system" | "center";
        };
        TemplateSession: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            sessionOrder: number;
        };
        ListTemplatesResult: {
            /**
             * @description System seeds + caller's center-owned templates. The response is
             *     guaranteed to contain at least the 5 system seeds (per AC1b); if
             *     fewer are found the handler responds `500 SEED_INCOMPLETE`
             *     rather than a spec-conformant short response. C2-13 review fix
             *     — the invariant was previously enforced only at runtime.
             */
            templates: components["schemas"]["Template"][];
        };
        CreateTemplateResult: {
            /** Format: uuid */
            id: string;
            name: string;
            targetBand: number;
            /** @enum {string} */
            primarySkill: "writing" | "speaking" | "listening" | "reading" | "listening_reading" | "all_skills";
            sessionCount: number;
            color: string | null;
            /** @enum {string} */
            scope: "center";
            sessions: components["schemas"]["TemplateSession"][];
        };
        SpawnClassInput: {
            cohortName: string;
            /**
             * Format: date
             * @description ISO-8601 date (YYYY-MM-DD). Must not be more than 30 days in the past.
             */
            startDate: string;
            /** Format: email */
            teacherEmail: string | null;
        };
        SpawnRequest: {
            classes: components["schemas"]["SpawnClassInput"][];
        };
        SpawnedClass: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date */
            startDate: string;
            /**
             * Format: uuid
             * @description Set for Branches A + B; null for Branches C + D.
             */
            teacherId: string | null;
            /**
             * Format: email
             * @description Set for Branches A + B (from `users.email`); null for Branches C + D — privacy per AC3 (do NOT leak "email exists in system").
             */
            teacherEmail: string | null;
            /**
             * Format: email
             * @description Set for Branch C only (from payload, normalized to lowercase); null otherwise.
             */
            pendingTeacherEmail: string | null;
            /** @enum {string} */
            teacherStatus: "assigned" | "invited" | "unassigned";
            /** @enum {string} */
            teacherAssignmentReason: "explicit_self" | "explicit_member" | "founder_auto" | "invited" | "unassigned";
        };
        SpawnInviteEntry: {
            /**
             * Format: email
             * @description Lowercased invited email.
             */
            email: string;
            /**
             * @description **0-indexed** payload-order class indices this invite covers.
             *     Clients rendering "invite N went to <email>" copy MUST convert
             *     to 1-based for display (C2-06 review fix — spec previously
             *     didn't specify the indexing base).
             */
            classIndices: number[];
            /** @description Return value of `EmailRetryQueue.Enqueue` for newly-created invites; false when reusing an existing invite or when the retry queue buffer is full. */
            enqueued: boolean;
            /** @description True when a pre-existing active invite was reused (dedup at DB via `idx_invites_center_email_active`); false when a new row was written this call. */
            reusedExistingInvite: boolean;
            /** Format: date-time */
            expiresAt: string;
        };
        SpawnResult: {
            classes: components["schemas"]["SpawnedClass"][];
            invites: components["schemas"]["SpawnInviteEntry"][];
            /** @description Count of newly-created invite rows that were also enqueued=true (dedup-reused OR buffer-full invites are excluded). */
            invitesSent: number;
        };
        EnvelopeMeta: {
            /**
             * Format: date-time
             * @description ISO-8601 UTC timestamp at response render time. Clients use this instead of Date.now() for skew-immune "N seconds ago" affordances.
             */
            serverTime: string;
        };
        EnvelopeRegisterResult: {
            data: components["schemas"]["RegisterResult"];
        };
        EnvelopeVerifyEmailResult: {
            data: components["schemas"]["VerifyEmailResult"];
        };
        EnvelopeResendResult: {
            data: components["schemas"]["ResendResult"];
        };
        EnvelopeVerifyStatusResult: {
            data: components["schemas"]["VerifyStatusResult"];
        };
        EnvelopeLoginResult: {
            data: components["schemas"]["LoginResult"];
        };
        EnvelopeLogoutResult: {
            data: components["schemas"]["LogoutResult"];
        };
        EnvelopeForgotPasswordResult: {
            data: components["schemas"]["ForgotPasswordResult"];
        };
        EnvelopeResetPasswordResult: {
            data: components["schemas"]["ResetPasswordResult"];
        };
        EnvelopeSetPersonaResult: {
            data: components["schemas"]["SetPersonaResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopeCreateCenterResult: {
            data: components["schemas"]["CreateCenterResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopeCenterProfile: {
            data: components["schemas"]["CenterProfile"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopeOnboardingProgress: {
            data: components["schemas"]["OnboardingProgressResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopePutOnboardingProgressResult: {
            data: components["schemas"]["PutOnboardingProgressResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopeListTemplatesResult: {
            data: components["schemas"]["ListTemplatesResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopeCreateTemplateResult: {
            data: components["schemas"]["CreateTemplateResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        EnvelopeSpawnResult: {
            data: components["schemas"]["SpawnResult"];
            meta: components["schemas"]["EnvelopeMeta"];
        };
        FieldError: {
            field: string;
            /**
             * @description Optional per-field UPPER_SNAKE_CASE identifier (e.g.
             *     INVALID_TEACHER_EMAIL, SELF_INVITE_BLOCKED) — populated for
             *     error-catalog fields; empty string OR omitted when the error
             *     carries only a prose message. Story 1.x handlers pre-date the
             *     catalog and emit `""` for `code`; Story 2.2+ handlers populate
             *     it where the wizard router needs to key on the field-level
             *     code. C2-03 review fix — was `required` under Story 2.2's
             *     initial pass, which broke JSON-Schema validators for pre-2.2
             *     envelopes that didn't emit the key.
             */
            code?: string;
            message: string;
        };
        ErrorBody: {
            /** @description UPPER_SNAKE_CASE error code (e.g., VALIDATION_ERROR, EMAIL_ALREADY_REGISTERED, VERIFICATION_TOKEN_EXPIRED). */
            code: string;
            message: string;
            requestId: string;
            details: null | components["schemas"]["FieldError"][];
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        AcceptInviteRequest: {
            inviteToken: string;
            /** @description Required only on the new-user branch. */
            fullName?: string | null;
            /** @description Required only on the new-user branch. */
            password?: string | null;
        };
        InviteCenter: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        AcceptInviteResult: {
            accessToken: string;
            user: components["schemas"]["UserSummary"];
            center: components["schemas"]["InviteCenter"];
            /** @enum {string} */
            role: "owner" | "admin" | "teacher" | "student";
        };
        EnvelopeAcceptInviteResult: {
            data: components["schemas"]["AcceptInviteResult"];
        };
        ForceLogoutResult: {
            forcedLogout: boolean;
            /** @description Number of refresh_tokens rows deleted for the target. */
            sessionsRevoked: number;
        };
        EnvelopeForceLogoutResult: {
            data: components["schemas"]["ForceLogoutResult"];
        };
        InviteExpiredDetails: {
            centerName: string;
            /** Format: email */
            inviterEmail: string;
        };
        InviteAlreadyAcceptedDetails: {
            centerName: string;
        };
        InviteEmailMismatchDetails: {
            /** Format: email */
            invitedEmail: string;
            /** Format: email */
            oauthEmail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeRegisterResult"];
                };
            };
            /** @description Email already registered (ambiguous — does not reveal verification status) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Per-IP rate limit exceeded (token bucket — burst 5, replenishment 1 every 2 min) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Verified (or idempotent replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeVerifyEmailResult"];
                };
            };
            /** @description Token does not exist (VERIFICATION_TOKEN_INVALID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description Token expired — the link is older than 24 hours and the user has
             *     not verified yet (VERIFICATION_TOKEN_EXPIRED). Rotated-out tokens
             *     (a newer resend has been issued) DO NOT return 410 on their own —
             *     once the user is verified, replaying any prior-issued token
             *     returns 200 idempotent.
             */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure (missing token) or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /**
             * @description Ambiguous success. `verifyPollId` is null when the email is
             *     unknown or already verified.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeResendResult"];
                };
            };
            /** @description Invalid email format or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description Rate limit exceeded — either the per-IP token bucket (burst 5, 1
             *     token / 2 min) or the per-email bucket (1 token / 60 s).
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Set-Cookie carries the refresh token (httpOnly, Secure, SameSite=Lax, Domain=.classlite.app). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeLoginResult"];
                };
            };
            /** @description INVALID_CREDENTIALS — wrong email or password (indistinguishable from unknown email). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description ACCOUNT_LOCKED (5 failed attempts in 10 min, locked 15 min) OR per-IP RATE_LIMIT_EXCEEDED. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated. New refresh cookie set; new access token in body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeLoginResult"];
                };
            };
            /** @description REFRESH_TOKEN_INVALID (no row + no family) or REFRESH_TOKEN_REUSE_DETECTED (family revoked). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. Set-Cookie clears the refresh cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeLogoutResult"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Ambiguous success. Reset email may or may not have been sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeForgotPasswordResult"];
                };
            };
            /** @description Invalid email format or malformed body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Per-IP (5 / 2min) or per-email (3 / 60s) rate-limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeResetPasswordResult"];
                };
            };
            /** @description RESET_TOKEN_INVALID — token does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESET_TOKEN_CONSUMED — token was already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESET_TOKEN_EXPIRED — token TTL elapsed. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure (password length) or malformed body. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    googleInit: {
        parameters: {
            query?: {
                inviteToken?: string;
                redirectTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google authorization URL. Sets `oauth_state` cookie. */
            302: {
                headers: {
                    /** @description Google's authorization URL with `state=<signed>` query param. */
                    Location?: string;
                    /**
                     * @description `oauth_state=<signed>; HttpOnly; Secure; SameSite=Lax; Path=/api/auth; Max-Age=600`
                     *     (Domain set in non-dev).
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_INVITE_TOKEN — supplied token exceeds the 256-char cap. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_NOT_FOUND — inviteToken was supplied but the invite no longer exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_ALREADY_ACCEPTED — the invite has already been redeemed. Details carry `{ centerName }`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_EXPIRED — inviteToken was supplied but the invite has expired. Details carry `{ centerName, inviterEmail }`. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description OAUTH_NOT_CONFIGURED — operator left Google credentials empty (dev parity only). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    googleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser-navigation redirect — success or failure carries the outcome in the Location query string. */
            302: {
                headers: {
                    Location?: string;
                    /**
                     * @description `refresh_token=<value>` on success (per AC10 from story 1.5)
                     *     AND `oauth_state=; Max-Age=0` (replay defense).
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Invite accepted, session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeAcceptInviteResult"];
                };
            };
            /** @description INVITE_NOT_FOUND — the token does not match a row. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_ALREADY_ACCEPTED / INVITE_EMAIL_MISMATCH / PASSWORD_NOT_ALLOWED_FOR_OAUTH_USER / GOOGLE_ID_ALREADY_LINKED. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_EXPIRED — surfaces details `{ centerName, inviterEmail }` so the SPA can render UX recovery. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description VALIDATION_ERROR — missing fullName/password on new-user branch, or malformed body. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Per-IP rate limit (10 / 60s) exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    forceLogout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeForceLogoutResult"];
                };
            };
            /** @description AUTH_REQUIRED — missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INSUFFICIENT_ROLE — caller is not an Owner. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description USER_NOT_FOUND — target does not exist in the caller's tenant (cross-tenant attempts also collapse here). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description VALIDATION_ERROR — malformed UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    verifyStatus: {
        parameters: {
            query: {
                pollId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current verification status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeVerifyStatusResult"];
                };
            };
            /** @description Poll ID not found, malformed, or expired (POLL_ID_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    setOnboardingPersona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPersonaRequest"];
            };
        };
        responses: {
            /** @description Persona persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeSetPersonaResult"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createCenter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCenterRequest"];
            };
        };
        responses: {
            /** @description Center created, caller bound as Owner, fresh JWT returned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeCreateCenterResult"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Caller already has a center (USER_ALREADY_HAS_CENTER) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Slug regeneration exhausted after 5 attempts (INTERNAL_ERROR) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCenterProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Center profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeCenterProfile"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description INSUFFICIENT_ROLE (non-Owner), TENANT_MISMATCH (path id ≠ caller's centerID),
             *     or EMAIL_VERIFICATION_REQUIRED.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Center not found (CENTER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal error (INTERNAL_ERROR) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateCenterProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCenterProfileRequest"];
            };
        };
        responses: {
            /** @description Updated center profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeCenterProfile"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description INSUFFICIENT_ROLE (non-Owner), TENANT_MISMATCH (path id ≠ caller's centerID),
             *     or EMAIL_VERIFICATION_REQUIRED.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Center not found (CENTER_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description Validation failure — name length, invalid contactEmail, or
             *     UNSUPPORTED_TIMEZONE (timezone not in 30-entry whitelist).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal error (INTERNAL_ERROR) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeListTemplatesResult"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED), caller has no center yet (CENTER_REQUIRED), tenant claim on JWT invalid (INVALID_TENANT_CLAIM), or generic forbidden (FORBIDDEN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Seed migration incomplete (SEED_INCOMPLETE) OR unexpected server error (INTERNAL_ERROR) — inspect `error.code` to route (C2-09 review fix) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Template created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeCreateTemplateResult"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED), caller has no center yet (CENTER_REQUIRED), tenant claim on JWT invalid (INVALID_TENANT_CLAIM), or generic forbidden (FORBIDDEN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure (VALIDATION_ERROR) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error (INTERNAL_ERROR) — C2-02 review fix (was undocumented) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    spawnClasses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpawnRequest"];
            };
        };
        responses: {
            /** @description All classes spawned atomically */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeSpawnResult"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED), caller has no center yet (CENTER_REQUIRED), tenant claim on JWT invalid (INVALID_TENANT_CLAIM), or generic forbidden (FORBIDDEN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Template does not exist or is invisible to caller (TEMPLATE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure (VALIDATION_ERROR at envelope level). `error.details[*].code` may include: `INVALID_TEACHER_EMAIL`, `SELF_INVITE_BLOCKED`. Other field-level codes are empty (`""`) and rely on `error.details[*].field` + `error.details[*].message` for surfacing (cohortName length, startDate drift, class count, malformed JSON). C2-08 review fix — the enumeration is not exhaustive. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (spawnLimit 5/min IP + onboardingLimit 20/min IP) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error (INTERNAL_ERROR) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getOnboardingProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress state (or default when unsaved) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeOnboardingProgress"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    putOnboardingProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutOnboardingProgressRequest"];
            };
        };
        responses: {
            /** @description Progress persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopePutOnboardingProgressResult"];
                };
            };
            /** @description Missing (AUTH_REQUIRED) or invalid (AUTH_INVALID) access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Email not verified (EMAIL_VERIFICATION_REQUIRED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded (RATE_LIMIT_EXCEEDED); Retry-After header carries the retry window in seconds */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
