/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the API
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email/password registration (story 1.4)
         * @description Creates a new user account and sends a verification email. The
         *     `emailDelivery` field in the response is always present:
         *     `"sent"` when the verification email was enqueued cleanly,
         *     `"failed"` when the retry queue rejected the job (buffer full — no
         *     async retry will occur; the client should prompt the user to hit
         *     Resend Verification). `"delayed"` is reserved for future use cases.
         *     Returns 409 EMAIL_ALREADY_REGISTERED for any duplicate regardless of
         *     verification status (anti-enumeration).
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify email via token (story 1.4)
         * @description Consumes the verification token, sets `users.email_verified = true`,
         *     and invalidates any other unconsumed tokens for the same user. The
         *     operation is idempotent — replaying any prior-issued token after the
         *     user is verified also returns 200.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend verification email (story 1.4)
         * @description Rotates the user's verification token (invalidating any prior
         *     unconsumed tokens) and sends a new email. Returns 200 with
         *     `verifyPollId: null` when the email is unknown OR already verified,
         *     to prevent enumeration. All 200 responses are padded to ≥ 200 ms.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email/password login (story 1.5)
         * @description Verifies credentials and issues a 15-minute access token + a refresh
         *     token (7d default, 30d with rememberMe). The refresh token is set as
         *     an httpOnly cookie (all four cookie attributes per AC10); the
         *     response body NEVER includes the refresh token. After 5 failed
         *     attempts within 10 minutes, the account is locked for 15 minutes —
         *     subsequent attempts (even with the correct password) return 429
         *     ACCOUNT_LOCKED with a Retry-After header.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate session tokens (story 1.5)
         * @description Atomically DELETEs the presented refresh token row and INSERTs a
         *     fresh one in the same family. Reuse of a rotated-out token triggers
         *     family revocation (every refresh in the family is deleted), and the
         *     response is 401 REFRESH_TOKEN_REUSE_DETECTED.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate refresh token and clear cookie (story 1.5)
         * @description Hard-deletes the matching refresh_tokens row and emits a clearing
         *     Set-Cookie. Idempotent — unknown / missing / already-revoked
         *     cookies still return 200.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password-reset email (story 1.5)
         * @description Sends a reset email (1 hour TTL) when the email is known and
         *     verified. Returns the same 200 envelope for unknown / unverified
         *     emails — anti-enumeration. All 200 responses are padded to ≥ 200ms.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply password reset (story 1.5)
         * @description Consumes the reset token, updates the password, DELETEs every
         *     refresh_tokens row for the user (force re-login everywhere), and
         *     clears login_attempts. Replaying a consumed token returns 409
         *     RESET_TOKEN_CONSUMED; an expired token returns 410
         *     RESET_TOKEN_EXPIRED.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate Google OAuth sign-in (story 1.6)
         * @description Generates a CSRF-bound signed state token, sets the `oauth_state`
         *     httpOnly cookie (Path=/api/auth, Max-Age=600), and 302-redirects to
         *     Google's authorization URL. Optional `inviteToken` is verified
         *     pre-flight to short-circuit a wasted Google round-trip; `redirectTo`
         *     is honored only when it matches the same-origin allowlist.
         */
        get: operations["googleInit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth callback (story 1.6)
         * @description Always returns 302. Success → `APP_POST_LOGIN_URL` plus
         *     `?invited=true&center=<name>` when an invite was accepted, or
         *     `?error=<code>` for invite-recoverable failures. Failure →
         *     `APP_LOGIN_ERROR_URL_BASE?error=<code>`. Codes: `csrf_invalid`,
         *     `csrf_expired`, `google_exchange_failed`, `google_userinfo_failed`,
         *     `google_timeout`, `google_email_unverified`, `google_access_denied`,
         *     `google_server_error`, `oauth_wrong_tenant`, `google_link_race`,
         *     `invite_email_mismatch`, `invite_expired`, `invite_already_accepted`.
         *     The `oauth_state` cookie is cleared on every exit path.
         *     OAUTH_NOT_CONFIGURED is the only response that is NOT a 302 — it
         *     emits a 503 JSON envelope so operator monitoring picks it up.
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a staff invite via email/password (story 1.6)
         * @description Two branches based on whether the invite email matches an existing
         *     user. New users supply `fullName` + `password`; existing users
         *     omit both. The invite link is the email verification — accepted
         *     users land with `emailVerified: true`. Per-IP rate limited
         *     (10 / 60s) to defend against token enumeration.
         */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/force-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Owner-initiated force-logout for a staff member (story 1.6 / FR-80)
         * @description Bulk-deletes every `refresh_tokens` row for the target user.
         *     Documented limitation: access tokens already issued remain valid
         *     for up to AccessTokenTTL (15 min) — EDGE-2 tradeoff accepted.
         *     Cross-tenant targets return 404 USER_NOT_FOUND (NEVER 403, which
         *     would leak existence). Requires authenticated Owner JWT.
         */
        post: operations["forceLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll current verification state (story 1.4)
         * @description Returns the user's current `emailVerified` state given a poll ID. The
         *     poll ID is the `email_verifications.id` of the row issued at
         *     registration or resend. Poll IDs expire 24 hours after creation,
         *     matching the verification token TTL. Unknown, malformed, or expired
         *     poll IDs all return the same 404 POLL_ID_NOT_FOUND.
         */
        get: operations["verifyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        VerifyEmailRequest: {
            token: string;
        };
        ResendVerificationRequest: {
            /** Format: email */
            email: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @default false */
            rememberMe: boolean;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
            emailVerified: boolean;
        };
        RegisterResult: {
            user: components["schemas"]["UserSummary"];
            /** Format: uuid */
            verifyPollId: string;
            /**
             * @description `sent` — verification email was enqueued for delivery. `delayed` —
             *     reserved for future use when a send is genuinely postponed rather
             *     than dropped. `failed` — the retry queue rejected the job (buffer
             *     full); no async retry will occur. The frontend should prompt the
             *     user to hit Resend Verification when it sees `failed`.
             * @enum {string}
             */
            emailDelivery: "sent" | "delayed" | "failed";
        };
        VerifyEmailResult: {
            verified: boolean;
            /** Format: email */
            email: string;
        };
        ResendResult: {
            /** Format: uuid */
            verifyPollId: string | null;
        };
        VerifyStatusResult: {
            verified: boolean;
            /** Format: email */
            email: string;
        };
        LoginResult: {
            /** @description HS256-signed JWT, 15-minute expiry. */
            accessToken: string;
            user: components["schemas"]["UserSummary"];
        };
        LogoutResult: {
            loggedOut: boolean;
        };
        ForgotPasswordResult: {
            /** @description Always true on a 200 — does not indicate whether an email was actually dispatched (anti-enumeration). */
            sent: boolean;
        };
        ResetPasswordResult: {
            reset: boolean;
        };
        EnvelopeRegisterResult: {
            data: components["schemas"]["RegisterResult"];
        };
        EnvelopeVerifyEmailResult: {
            data: components["schemas"]["VerifyEmailResult"];
        };
        EnvelopeResendResult: {
            data: components["schemas"]["ResendResult"];
        };
        EnvelopeVerifyStatusResult: {
            data: components["schemas"]["VerifyStatusResult"];
        };
        EnvelopeLoginResult: {
            data: components["schemas"]["LoginResult"];
        };
        EnvelopeLogoutResult: {
            data: components["schemas"]["LogoutResult"];
        };
        EnvelopeForgotPasswordResult: {
            data: components["schemas"]["ForgotPasswordResult"];
        };
        EnvelopeResetPasswordResult: {
            data: components["schemas"]["ResetPasswordResult"];
        };
        FieldError: {
            field: string;
            message: string;
        };
        ErrorBody: {
            /** @description UPPER_SNAKE_CASE error code (e.g., VALIDATION_ERROR, EMAIL_ALREADY_REGISTERED, VERIFICATION_TOKEN_EXPIRED). */
            code: string;
            message: string;
            requestId: string;
            details: null | components["schemas"]["FieldError"][];
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        AcceptInviteRequest: {
            inviteToken: string;
            /** @description Required only on the new-user branch. */
            fullName?: string | null;
            /** @description Required only on the new-user branch. */
            password?: string | null;
        };
        InviteCenter: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        AcceptInviteResult: {
            accessToken: string;
            user: components["schemas"]["UserSummary"];
            center: components["schemas"]["InviteCenter"];
            /** @enum {string} */
            role: "owner" | "admin" | "teacher" | "student";
        };
        EnvelopeAcceptInviteResult: {
            data: components["schemas"]["AcceptInviteResult"];
        };
        ForceLogoutResult: {
            forcedLogout: boolean;
            /** @description Number of refresh_tokens rows deleted for the target. */
            sessionsRevoked: number;
        };
        EnvelopeForceLogoutResult: {
            data: components["schemas"]["ForceLogoutResult"];
        };
        InviteExpiredDetails: {
            centerName: string;
            /** Format: email */
            inviterEmail: string;
        };
        InviteAlreadyAcceptedDetails: {
            centerName: string;
        };
        InviteEmailMismatchDetails: {
            /** Format: email */
            invitedEmail: string;
            /** Format: email */
            oauthEmail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeRegisterResult"];
                };
            };
            /** @description Email already registered (ambiguous — does not reveal verification status) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Per-IP rate limit exceeded (token bucket — burst 5, replenishment 1 every 2 min) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Verified (or idempotent replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeVerifyEmailResult"];
                };
            };
            /** @description Token does not exist (VERIFICATION_TOKEN_INVALID) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description Token expired — the link is older than 24 hours and the user has
             *     not verified yet (VERIFICATION_TOKEN_EXPIRED). Rotated-out tokens
             *     (a newer resend has been issued) DO NOT return 410 on their own —
             *     once the user is verified, replaying any prior-issued token
             *     returns 200 idempotent.
             */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure (missing token) or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /**
             * @description Ambiguous success. `verifyPollId` is null when the email is
             *     unknown or already verified.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeResendResult"];
                };
            };
            /** @description Invalid email format or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description Rate limit exceeded — either the per-IP token bucket (burst 5, 1
             *     token / 2 min) or the per-email bucket (1 token / 60 s).
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Set-Cookie carries the refresh token (httpOnly, Secure, SameSite=Lax, Domain=.classlite.app). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeLoginResult"];
                };
            };
            /** @description INVALID_CREDENTIALS — wrong email or password (indistinguishable from unknown email). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure or malformed JSON body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description ACCOUNT_LOCKED (5 failed attempts in 10 min, locked 15 min) OR per-IP RATE_LIMIT_EXCEEDED. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated. New refresh cookie set; new access token in body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeLoginResult"];
                };
            };
            /** @description REFRESH_TOKEN_INVALID (no row + no family) or REFRESH_TOKEN_REUSE_DETECTED (family revoked). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. Set-Cookie clears the refresh cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeLogoutResult"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Ambiguous success. Reset email may or may not have been sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeForgotPasswordResult"];
                };
            };
            /** @description Invalid email format or malformed body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Per-IP (5 / 2min) or per-email (3 / 60s) rate-limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeResetPasswordResult"];
                };
            };
            /** @description RESET_TOKEN_INVALID — token does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESET_TOKEN_CONSUMED — token was already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description RESET_TOKEN_EXPIRED — token TTL elapsed. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation failure (password length) or malformed body. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    googleInit: {
        parameters: {
            query?: {
                inviteToken?: string;
                redirectTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google authorization URL. Sets `oauth_state` cookie. */
            302: {
                headers: {
                    /** @description Google's authorization URL with `state=<signed>` query param. */
                    Location?: string;
                    /**
                     * @description `oauth_state=<signed>; HttpOnly; Secure; SameSite=Lax; Path=/api/auth; Max-Age=600`
                     *     (Domain set in non-dev).
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_INVITE_TOKEN — supplied token exceeds the 256-char cap. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_NOT_FOUND — inviteToken was supplied but the invite no longer exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_ALREADY_ACCEPTED — the invite has already been redeemed. Details carry `{ centerName }`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_EXPIRED — inviteToken was supplied but the invite has expired. Details carry `{ centerName, inviterEmail }`. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description OAUTH_NOT_CONFIGURED — operator left Google credentials empty (dev parity only). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    googleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser-navigation redirect — success or failure carries the outcome in the Location query string. */
            302: {
                headers: {
                    Location?: string;
                    /**
                     * @description `refresh_token=<value>` on success (per AC10 from story 1.5)
                     *     AND `oauth_state=; Max-Age=0` (replay defense).
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Invite accepted, session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeAcceptInviteResult"];
                };
            };
            /** @description INVITE_NOT_FOUND — the token does not match a row. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_ALREADY_ACCEPTED / INVITE_EMAIL_MISMATCH / PASSWORD_NOT_ALLOWED_FOR_OAUTH_USER / GOOGLE_ID_ALREADY_LINKED. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INVITE_EXPIRED — surfaces details `{ centerName, inviterEmail }` so the SPA can render UX recovery. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description VALIDATION_ERROR — missing fullName/password on new-user branch, or malformed body. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Per-IP rate limit (10 / 60s) exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    forceLogout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeForceLogoutResult"];
                };
            };
            /** @description AUTH_REQUIRED — missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description INSUFFICIENT_ROLE — caller is not an Owner. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description USER_NOT_FOUND — target does not exist in the caller's tenant (cross-tenant attempts also collapse here). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description VALIDATION_ERROR — malformed UUID. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    verifyStatus: {
        parameters: {
            query: {
                pollId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current verification status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeVerifyStatusResult"];
                };
            };
            /** @description Poll ID not found, malformed, or expired (POLL_ID_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
